import type {
  Announcement,
  Assignment,
  AttendanceRecord,
  Commitment,
  Course,
  Lesson,
  MorningPicture,
  Staff,
  Student,
  UnderstandingSignal,
  Unit,
} from "@/types";
import type { ScheduleEntry } from "./types";

// Demo seed data — fallback dataset used when no canister actor is available.
// Extracted verbatim from useBackend.ts (no logic, pure data).

export const DEMO_STUDENTS: Student[] = [
  {
    id: "s1",
    firstName: "Jordan",
    lastName: "Ellis",
    dob: "2008-03-14",
    grade: 10,
    homeroom: "101A",
    guardians: [],
    specialPopulations: [],
    gpa: 3.7,
    attendanceRate: 96,
    trajectory: "thriving",
    enrolmentStatus: "active",
    counsellorId: "staff-6",
  },
  {
    id: "s2",
    firstName: "Maya",
    lastName: "Okonkwo",
    dob: "2008-07-22",
    grade: 10,
    homeroom: "101A",
    guardians: [],
    specialPopulations: [{ type: "iep" }],
    gpa: 2.4,
    attendanceRate: 78,
    trajectory: "slipping",
    enrolmentStatus: "active",
    counsellorId: "staff-7",
  },
  {
    id: "s3",
    firstName: "Tyler",
    lastName: "Reyes",
    dob: "2008-11-05",
    grade: 10,
    homeroom: "102B",
    guardians: [],
    specialPopulations: [{ type: "ell", wida_level: "3" }, { type: "iep" }],
    gpa: 3.1,
    attendanceRate: 91,
    trajectory: "steady",
    enrolmentStatus: "active",
    counsellorId: "staff-6",
  },
  {
    id: "s4",
    firstName: "Priya",
    lastName: "Sharma",
    dob: "2009-01-18",
    grade: 9,
    homeroom: "103C",
    guardians: [],
    specialPopulations: [],
    gpa: 3.9,
    attendanceRate: 99,
    trajectory: "thriving",
    enrolmentStatus: "active",
    counsellorId: "staff-7",
  },
  {
    id: "s5",
    firstName: "Marcus",
    lastName: "Brown",
    dob: "2007-09-30",
    grade: 11,
    homeroom: "201A",
    guardians: [],
    specialPopulations: [{ type: "iep" }],
    gpa: 2.9,
    attendanceRate: 84,
    trajectory: "coasting",
    enrolmentStatus: "active",
    counsellorId: "staff-7",
  },
  {
    id: "s6",
    firstName: "Aisha",
    lastName: "Williams",
    dob: "2007-04-12",
    grade: 11,
    homeroom: "201B",
    guardians: [],
    specialPopulations: [{ type: "gifted" }],
    gpa: 4.0,
    attendanceRate: 98,
    trajectory: "thriving",
    enrolmentStatus: "active",
    counsellorId: "staff-6",
  },
];

export const DEMO_STAFF: Staff[] = [
  {
    id: "staff-1",
    firstName: "Maria",
    lastName: "Chen",
    roles: ["teacher"],
    email: "mchen@lincoln.edu",
    department: "Math",
  },
  {
    id: "staff-2",
    firstName: "James",
    lastName: "Okafor",
    roles: ["coTeacher"],
    email: "jokafor@lincoln.edu",
    department: "Math",
  },
  {
    id: "staff-3",
    firstName: "Patricia",
    lastName: "Nguyen",
    roles: ["schoolAdmin"],
    email: "pnguyen@lincoln.edu",
  },
  {
    id: "staff-4",
    firstName: "Robert",
    lastName: "Kim",
    roles: ["departmentHead", "teacher"],
    email: "rkim@lincoln.edu",
    department: "Science",
  },
  {
    id: "staff-5",
    firstName: "Diana",
    lastName: "Walsh",
    roles: ["principal"],
    email: "dwalsh@lincoln.edu",
  },
  {
    id: "staff-6",
    firstName: "James",
    lastName: "Carter",
    roles: ["counsellor"],
    email: "jcarter@lincolnhigh.edu",
  },
  {
    id: "staff-7",
    firstName: "Sophia",
    lastName: "Martinez",
    roles: ["counsellor"],
    email: "sophia.martinez@lincolnhigh.edu",
    department: "Student Services",
  },
];

export const DEMO_COURSES: Course[] = [
  {
    id: "c1",
    name: "Algebra II",
    shortCode: "ALG2",
    teacherId: "staff-1",
    grade: 10,
    subject: "Mathematics",
    studentIds: ["s1", "s2", "s3"],
    period: 2,
    room: "201",
  },
  {
    id: "c2",
    name: "Pre-Calculus",
    shortCode: "PRECALC",
    teacherId: "staff-1",
    grade: 11,
    subject: "Mathematics",
    studentIds: ["s5", "s6"],
    period: 4,
    room: "201",
  },
  {
    id: "c3",
    name: "Biology Honors",
    shortCode: "BIOH",
    teacherId: "staff-4",
    grade: 10,
    subject: "Science",
    studentIds: ["s1", "s4"],
    period: 3,
    room: "115",
  },
];

export const DEMO_SIGNALS: UnderstandingSignal[] = [
  {
    id: "sig1",
    studentId: "s2",
    type: "risk",
    urgency: "high",
    headline: "Maya needs a check-in",
    reason:
      "Attendance at 78%, Algebra dropped a letter grade, recent behaviour incidents flagged.",
    forRoles: ["teacher", "counsellor", "principal"],
    generatedAt: new Date().toISOString(),
    acknowledged: false,
  },
  {
    id: "sig2",
    studentId: "s1",
    type: "opportunity",
    urgency: "low",
    headline: "Jordan ready to be stretched",
    reason: "Consistently A in Algebra II — could take the extension module.",
    forRoles: ["teacher", "departmentHead"],
    generatedAt: new Date().toISOString(),
    acknowledged: false,
  },
  {
    id: "sig3",
    studentId: "s6",
    type: "celebration",
    urgency: "low",
    headline: "Aisha aced the district benchmark",
    reason: "Top score in the grade 11 cohort. Worth a note home.",
    forRoles: ["teacher", "principal", "parent"],
    generatedAt: new Date().toISOString(),
    acknowledged: false,
  },
  {
    id: "sig4",
    studentId: "s5",
    type: "workload",
    urgency: "medium",
    headline: "Assessment clash this week",
    reason:
      "Marcus has 3 major assessments in one week across Algebra, History, and English.",
    forRoles: ["teacher", "principal"],
    generatedAt: new Date().toISOString(),
    acknowledged: false,
  },
  {
    id: "sig5",
    studentId: "s3",
    type: "pattern",
    urgency: "medium",
    headline: "Tyler late twice this week",
    reason:
      "Late to Biology Honors on Monday and Wednesday. No hall pass either time.",
    forRoles: ["teacher", "counsellor"],
    generatedAt: new Date().toISOString(),
    acknowledged: false,
  },
  {
    id: "sig6",
    studentId: "s1",
    type: "workload",
    urgency: "low",
    headline: "Jordan has 2 tests tomorrow",
    reason:
      "Algebra II unit test and Biology quiz both scheduled for Thursday.",
    forRoles: ["teacher", "parent"],
    generatedAt: new Date().toISOString(),
    acknowledged: false,
  },
];

export const DEMO_COMMITMENTS: Commitment[] = [
  {
    id: "com1",
    type: "counsellor_followup",
    ownerId: "staff-7",
    studentId: "s2",
    description: "Follow-up check-in with Maya re: attendance pattern",
    dueDate: "2026-06-15",
    status: "due_soon",
  },
  {
    id: "com2",
    type: "iep_renewal",
    ownerId: "staff-8",
    studentId: "s2",
    description: "IEP annual renewal due for Maya Okonkwo",
    dueDate: "2026-06-20",
    status: "due_soon",
  },
  {
    id: "com3",
    type: "conference",
    ownerId: "staff-1",
    studentId: "s2",
    description: "Parent conference re: Maya progress",
    dueDate: "2026-06-18",
    status: "pending",
  },
  {
    id: "com4",
    type: "permission_slip",
    ownerId: "parent-1",
    studentId: "s1",
    description: "Science Field Trip permission slip unsigned",
    dueDate: "2026-06-14",
    status: "overdue",
  },
  {
    id: "com5",
    type: "iep_renewal",
    ownerId: "staff-8",
    studentId: "s3",
    description: "IEP annual renewal due for Tyler Reyes",
    dueDate: "2026-06-18",
    status: "due_soon",
  },
  {
    id: "com6",
    type: "iep_renewal",
    ownerId: "staff-8",
    studentId: "s5",
    description: "IEP annual renewal due for Marcus Brown",
    dueDate: "2026-07-10",
    status: "pending",
  },
  {
    id: "com7",
    type: "iep_renewal",
    ownerId: "staff-8",
    studentId: "s4",
    description: "IEP annual renewal due for Priya Sharma",
    dueDate: "2026-09-01",
    status: "pending",
  },
];

export const DEMO_ASSIGNMENTS: Assignment[] = [
  {
    id: "a1",
    courseId: "c1",
    title: "Unit 5 Test",
    dueDate: new Date().toISOString().slice(0, 10),
    weight: 0.25,
    maxPoints: 100,
    isHighStakes: true,
  },
  {
    id: "a2",
    courseId: "c3",
    title: "Lab Report — Osmosis",
    dueDate: new Date(Date.now() + 2 * 86400000).toISOString().slice(0, 10),
    weight: 0.15,
    maxPoints: 50,
    isHighStakes: false,
  },
  {
    id: "a3",
    courseId: "c1",
    title: "Problem Set 4.2",
    dueDate: new Date(Date.now() + 1 * 86400000).toISOString().slice(0, 10),
    weight: 0.05,
    maxPoints: 20,
    isHighStakes: false,
  },
  {
    id: "a4",
    courseId: "c2",
    title: "Trig Functions Quiz",
    dueDate: new Date(Date.now() + 3 * 86400000).toISOString().slice(0, 10),
    weight: 0.1,
    maxPoints: 30,
    isHighStakes: false,
  },
  {
    id: "a5",
    courseId: "c3",
    title: "Cell Division Worksheet",
    dueDate: new Date(Date.now() + 5 * 86400000).toISOString().slice(0, 10),
    weight: 0.05,
    maxPoints: 15,
    isHighStakes: false,
  },
];

export const DEMO_UNITS: Unit[] = [
  {
    id: "unit-1",
    courseId: "c1",
    title: "Algebra Fundamentals",
    description: "Introduction to algebraic concepts",
    order: 1,
    lessonCount: 4,
  },
  {
    id: "unit-2",
    courseId: "c1",
    title: "Quadratic Equations",
    description: "Solving second-degree polynomial equations",
    order: 2,
    lessonCount: 3,
  },
  {
    id: "unit-3",
    courseId: "c1",
    title: "Geometry Basics",
    description: "Shapes, angles, and measurements",
    order: 3,
    lessonCount: 4,
  },
  {
    id: "unit-4",
    courseId: "c2",
    title: "Literary Analysis",
    description: "Analyzing fiction and poetry",
    order: 1,
    lessonCount: 5,
  },
  {
    id: "unit-5",
    courseId: "c2",
    title: "Creative Writing",
    description: "Narrative and expository writing",
    order: 2,
    lessonCount: 4,
  },
  {
    id: "unit-6",
    courseId: "c2",
    title: "Research Skills",
    description: "Academic research and citation",
    order: 3,
    lessonCount: 3,
  },
  {
    id: "unit-7",
    courseId: "c3",
    title: "Cell Biology",
    description: "Cell structure and function",
    order: 1,
    lessonCount: 4,
  },
  {
    id: "unit-8",
    courseId: "c3",
    title: "Genetics",
    description: "Heredity and genetic variation",
    order: 2,
    lessonCount: 4,
  },
  {
    id: "unit-9",
    courseId: "c3",
    title: "Ecology",
    description: "Ecosystems and environmental interactions",
    order: 3,
    lessonCount: 3,
  },
];

export const DEMO_LESSONS: Lesson[] = [
  {
    id: "lesson-1",
    unitId: "unit-1",
    courseId: "c1",
    title: "Variables and Expressions",
    description: "Introduction to variables",
    order: 1,
    assignmentIds: ["a1"],
  },
  {
    id: "lesson-2",
    unitId: "unit-1",
    courseId: "c1",
    title: "Linear Equations",
    description: "Solving single-variable equations",
    order: 2,
    assignmentIds: ["a3"],
  },
  {
    id: "lesson-3",
    unitId: "unit-1",
    courseId: "c1",
    title: "Inequalities",
    description: "Solving and graphing inequalities",
    order: 3,
    assignmentIds: [],
  },
  {
    id: "lesson-4",
    unitId: "unit-2",
    courseId: "c1",
    title: "Factoring Quadratics",
    description: "Factor and solve quadratic equations",
    order: 1,
    assignmentIds: ["a1"],
  },
  {
    id: "lesson-5",
    unitId: "unit-4",
    courseId: "c2",
    title: "Short Story Elements",
    description: "Plot, character, setting, theme",
    order: 1,
    assignmentIds: ["a2"],
  },
  {
    id: "lesson-6",
    unitId: "unit-7",
    courseId: "c3",
    title: "Cell Structure",
    description: "Prokaryotic and eukaryotic cells",
    order: 1,
    assignmentIds: [],
  },
];

export const DEMO_TEACHER_ASSIGNMENTS = [
  {
    id: "assign-1",
    courseId: "c1",
    title: "Algebra Quiz 1",
    type: "quiz",
    dueDate: Date.now() - 7 * 86400000,
    points: 50,
    submissionCount: 42,
    totalStudents: 50,
    weight: 10,
  },
  {
    id: "assign-2",
    courseId: "c1",
    title: "Linear Equations Homework",
    type: "homework",
    dueDate: Date.now() - 14 * 86400000,
    points: 20,
    submissionCount: 48,
    totalStudents: 50,
    weight: 5,
  },
  {
    id: "assign-3",
    courseId: "c1",
    title: "Midterm Exam",
    type: "test",
    dueDate: Date.now() - 21 * 86400000,
    points: 100,
    submissionCount: 50,
    totalStudents: 50,
    weight: 25,
  },
  {
    id: "assign-4",
    courseId: "c1",
    title: "Geometry Project",
    type: "project",
    dueDate: Date.now() + 7 * 86400000,
    points: 75,
    submissionCount: 12,
    totalStudents: 50,
    weight: 20,
  },
  {
    id: "assign-5",
    courseId: "c1",
    title: "Algebra Final Exam",
    type: "test",
    dueDate: Date.now() + 21 * 86400000,
    points: 150,
    submissionCount: 0,
    totalStudents: 50,
    weight: 30,
  },
  {
    id: "assign-6",
    courseId: "c2",
    title: "Short Story Analysis",
    type: "essay",
    dueDate: Date.now() - 5 * 86400000,
    points: 50,
    submissionCount: 27,
    totalStudents: 30,
    weight: 15,
  },
  {
    id: "assign-7",
    courseId: "c2",
    title: "Vocabulary Quiz 1",
    type: "quiz",
    dueDate: Date.now() - 3 * 86400000,
    points: 30,
    submissionCount: 29,
    totalStudents: 30,
    weight: 10,
  },
];

export const DEMO_STUDENT_ASSIGNMENTS = [
  {
    id: "sa-1",
    assignmentId: "assign-3",
    courseId: "c1",
    courseName: "Algebra II",
    title: "Midterm Exam",
    type: "test",
    dueDate: Date.now() - 21 * 86400000,
    points: 100,
    submissionStatus: "graded" as const,
    earnedPoints: 82,
  },
  {
    id: "sa-2",
    assignmentId: "assign-1",
    courseId: "c1",
    courseName: "Algebra II",
    title: "Algebra Quiz 1",
    type: "quiz",
    dueDate: Date.now() - 7 * 86400000,
    points: 50,
    submissionStatus: "graded" as const,
    earnedPoints: 41,
  },
  {
    id: "sa-3",
    assignmentId: "assign-4",
    courseId: "c1",
    courseName: "Algebra II",
    title: "Geometry Project",
    type: "project",
    dueDate: Date.now() + 7 * 86400000,
    points: 75,
    submissionStatus: "submitted" as const,
  },
  {
    id: "sa-4",
    assignmentId: "assign-5",
    courseId: "c1",
    courseName: "Algebra II",
    title: "Algebra Final Exam",
    type: "test",
    dueDate: Date.now() + 21 * 86400000,
    points: 150,
    submissionStatus: "notSubmitted" as const,
  },
  {
    id: "sa-5",
    assignmentId: "assign-6",
    courseId: "c2",
    courseName: "Pre-Calculus",
    title: "Short Story Analysis",
    type: "essay",
    dueDate: Date.now() - 5 * 86400000,
    points: 50,
    submissionStatus: "graded" as const,
    earnedPoints: 46,
  },
  {
    id: "sa-6",
    assignmentId: "assign-7",
    courseId: "c2",
    courseName: "Pre-Calculus",
    title: "Vocabulary Quiz 1",
    type: "quiz",
    dueDate: Date.now() - 3 * 86400000,
    points: 30,
    submissionStatus: "graded" as const,
    earnedPoints: 28,
  },
  {
    id: "sa-7",
    courseId: "c3",
    courseName: "Biology Honors",
    title: "Cell Structure Quiz",
    type: "quiz",
    dueDate: Date.now() + 2 * 86400000,
    points: 40,
    submissionStatus: "notSubmitted" as const,
  },
  {
    id: "sa-8",
    courseId: "c3",
    courseName: "Biology Honors",
    title: "Lab Report: Osmosis",
    type: "project",
    dueDate: Date.now() - 2 * 86400000,
    points: 60,
    submissionStatus: "submitted" as const,
  },
];

export const DEMO_STUDENT_GRADES_NEW: Record<
  string,
  {
    gpa: number;
    letterGrade: string;
    courses: {
      courseId: string;
      courseName: string;
      grade: number;
      letterGrade: string;
      trend: number[];
      assignmentCount: number;
    }[];
  }
> = {
  s1: {
    gpa: 3.1,
    letterGrade: "B",
    courses: [
      {
        courseId: "c1",
        courseName: "Algebra II",
        grade: 82,
        letterGrade: "B",
        trend: [78, 80, 82],
        assignmentCount: 5,
      },
      {
        courseId: "c2",
        courseName: "Pre-Calculus",
        grade: 91,
        letterGrade: "A-",
        trend: [88, 90, 91],
        assignmentCount: 4,
      },
      {
        courseId: "c3",
        courseName: "Biology Honors",
        grade: 71,
        letterGrade: "C",
        trend: [75, 73, 71],
        assignmentCount: 3,
      },
    ],
  },
};

export const DEMO_CLASS_REPORT: Record<
  string,
  {
    students: {
      studentId: string;
      name: string;
      grade: number;
      letterGrade: string;
      attendanceRate: number;
      status: string;
    }[];
  }
> = {
  c1: {
    students: [
      {
        studentId: "s1",
        name: "Jordan Ellis",
        grade: 92,
        letterGrade: "A",
        attendanceRate: 96,
        status: "thriving",
      },
      {
        studentId: "s2",
        name: "Maya Okonkwo",
        grade: 71,
        letterGrade: "C+",
        attendanceRate: 78,
        status: "slipping",
      },
      {
        studentId: "s3",
        name: "Tyler Reyes",
        grade: 84,
        letterGrade: "B",
        attendanceRate: 91,
        status: "steady",
      },
      {
        studentId: "s4",
        name: "Priya Sharma",
        grade: 95,
        letterGrade: "A",
        attendanceRate: 99,
        status: "thriving",
      },
      {
        studentId: "s5",
        name: "Marcus Brown",
        grade: 76,
        letterGrade: "C+",
        attendanceRate: 84,
        status: "coasting",
      },
      {
        studentId: "s6",
        name: "Aisha Williams",
        grade: 98,
        letterGrade: "A",
        attendanceRate: 98,
        status: "thriving",
      },
      {
        studentId: "s7",
        name: "Liam Chen",
        grade: 88,
        letterGrade: "B+",
        attendanceRate: 94,
        status: "steady",
      },
      {
        studentId: "s8",
        name: "Sofia Martinez",
        grade: 81,
        letterGrade: "B-",
        attendanceRate: 89,
        status: "steady",
      },
      {
        studentId: "s9",
        name: "Noah Johnson",
        grade: 73,
        letterGrade: "C",
        attendanceRate: 82,
        status: "slipping",
      },
      {
        studentId: "s10",
        name: "Zara Ahmed",
        grade: 90,
        letterGrade: "A-",
        attendanceRate: 97,
        status: "thriving",
      },
    ],
  },
};

export const DEMO_THREADS = [
  {
    id: "thread-1",
    subject: "Algebra Quiz Grade",
    participants: [
      { id: "parent-1", name: "Maria Garcia", role: "parent" },
      { id: "teacher-1", name: "Sarah Johnson", role: "teacher" },
    ],
    lastMessage: "Thank you for explaining. I will help her review.",
    lastMessageAt: Date.now() - 2 * 3600000,
    unreadCount: 0,
    messageCount: 4,
  },
  {
    id: "thread-2",
    subject: "Attendance Concern - Emma Garcia",
    participants: [
      { id: "teacher-1", name: "Sarah Johnson", role: "teacher" },
      { id: "parent-1", name: "Maria Garcia", role: "parent" },
    ],
    lastMessage: "Emma was marked absent on Thursday — wanted to follow up.",
    lastMessageAt: Date.now() - 1 * 86400000,
    unreadCount: 1,
    messageCount: 2,
  },
  {
    id: "thread-3",
    subject: "Follow-up: Counsellor Check-in",
    participants: [
      { id: "counsellor-1", name: "James Carter", role: "counsellor" },
      { id: "student-1", name: "Emma Garcia", role: "student" },
    ],
    lastMessage: "I am glad things are going better. See you next Tuesday.",
    lastMessageAt: Date.now() - 3 * 86400000,
    unreadCount: 0,
    messageCount: 3,
  },
  {
    id: "thread-4",
    subject: "Professional Development Day - May 20",
    participants: [
      { id: "principal-1", name: "Dr. Kim Wells", role: "principal" },
      { id: "teacher-1", name: "Sarah Johnson", role: "teacher" },
    ],
    lastMessage: "Please confirm attendance by Friday.",
    lastMessageAt: Date.now() - 4 * 86400000,
    unreadCount: 1,
    messageCount: 2,
  },
  {
    id: "thread-5",
    subject: "Question about Biology homework",
    participants: [
      { id: "student-1", name: "Emma Garcia", role: "student" },
      { id: "teacher-3", name: "David Reyes", role: "teacher" },
    ],
    lastMessage: "Got it, thank you! I will redo section 3.",
    lastMessageAt: Date.now() - 5 * 86400000,
    unreadCount: 0,
    messageCount: 3,
  },
];

export const DEMO_MESSAGES: Record<
  string,
  {
    id: string;
    senderId: string;
    senderName: string;
    senderRole: string;
    body: string;
    sentAt: number;
  }[]
> = {
  "thread-1": [
    {
      id: "m1",
      senderId: "teacher-1",
      senderName: "Sarah Johnson",
      senderRole: "teacher",
      body: "Hi Maria, Emma scored 82% on the Algebra quiz. She did well on the equations section but struggled a bit with factoring. I have attached some practice problems.",
      sentAt: Date.now() - 6 * 3600000,
    },
    {
      id: "m2",
      senderId: "parent-1",
      senderName: "Maria Garcia",
      senderRole: "parent",
      body: "Thank you for letting me know. Is there anything specific she should focus on at home?",
      sentAt: Date.now() - 4 * 3600000,
    },
    {
      id: "m3",
      senderId: "teacher-1",
      senderName: "Sarah Johnson",
      senderRole: "teacher",
      body: "The practice problems cover exactly the areas she missed. About 15 minutes a day for the next week should help.",
      sentAt: Date.now() - 3 * 3600000,
    },
    {
      id: "m4",
      senderId: "parent-1",
      senderName: "Maria Garcia",
      senderRole: "parent",
      body: "Thank you for explaining. I will help her review.",
      sentAt: Date.now() - 2 * 3600000,
    },
  ],
  "thread-2": [
    {
      id: "m1",
      senderId: "teacher-1",
      senderName: "Sarah Johnson",
      senderRole: "teacher",
      body: "Emma was marked absent on Thursday — wanted to follow up and make sure everything is okay.",
      sentAt: Date.now() - 1.5 * 86400000,
    },
    {
      id: "m2",
      senderId: "parent-1",
      senderName: "Maria Garcia",
      senderRole: "parent",
      body: "She had a doctor's appointment that morning. I sent a note to the office but it may not have reached you yet. She will be back on Monday.",
      sentAt: Date.now() - 1 * 86400000,
    },
  ],
  "thread-3": [
    {
      id: "m1",
      senderId: "counsellor-1",
      senderName: "James Carter",
      senderRole: "counsellor",
      body: "Hi Emma, just checking in after our last meeting. How are you feeling about your classes this week?",
      sentAt: Date.now() - 4 * 86400000,
    },
    {
      id: "m2",
      senderId: "student-1",
      senderName: "Emma Garcia",
      senderRole: "student",
      body: "Things are going better. I turned in the Biology lab report and I am catching up in Math.",
      sentAt: Date.now() - 3.5 * 86400000,
    },
    {
      id: "m3",
      senderId: "counsellor-1",
      senderName: "James Carter",
      senderRole: "counsellor",
      body: "I am glad things are going better. See you next Tuesday.",
      sentAt: Date.now() - 3 * 86400000,
    },
  ],
  "thread-4": [
    {
      id: "m1",
      senderId: "principal-1",
      senderName: "Dr. Kim Wells",
      senderRole: "principal",
      body: "All staff are required to attend the professional development day on May 20th. Classes will not be held.",
      sentAt: Date.now() - 4.5 * 86400000,
    },
    {
      id: "m2",
      senderId: "teacher-1",
      senderName: "Sarah Johnson",
      senderRole: "teacher",
      body: "Please confirm attendance by Friday.",
      sentAt: Date.now() - 4 * 86400000,
    },
  ],
  "thread-5": [
    {
      id: "m1",
      senderId: "student-1",
      senderName: "Emma Garcia",
      senderRole: "student",
      body: "Hi Mr. Reyes, I am confused about question 3 on the Biology homework. Could you clarify what you are looking for?",
      sentAt: Date.now() - 5.5 * 86400000,
    },
    {
      id: "m2",
      senderId: "teacher-3",
      senderName: "David Reyes",
      senderRole: "teacher",
      body: "Question 3 asks for the difference between osmosis and diffusion. Focus on the membrane requirement.",
      sentAt: Date.now() - 5.2 * 86400000,
    },
    {
      id: "m3",
      senderId: "student-1",
      senderName: "Emma Garcia",
      senderRole: "student",
      body: "Got it, thank you! I will redo section 3.",
      sentAt: Date.now() - 5 * 86400000,
    },
  ],
};

export const DEMO_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "ann-1",
    title: "Lincoln High Spring Festival",
    body: "Join us on May 15th for our annual Spring Festival. Students, parents, and staff are all welcome. Food, games, and live performances from the fine arts department.",
    authorId: "admin-1",
    authorName: "School Admin",
    authorRole: "schoolAdmin",
    targetRoles: ["teacher", "student", "parent", "principal"],
    priority: "normal",
    createdAt: Date.now() - 2 * 86400000,
  },
  {
    id: "ann-2",
    title: "Professional Development Day — May 20",
    body: "All staff are required to attend the professional development day on May 20th. Classes will not be held. Details will be shared by department heads.",
    authorId: "principal-1",
    authorName: "Dr. Kim Wells",
    authorRole: "principal",
    targetRoles: [
      "teacher",
      "coTeacher",
      "departmentHead",
      "counsellor",
      "spedCoordinator",
      "curriculumCoordinator",
      "substitute",
    ],
    priority: "important",
    createdAt: Date.now() - 3 * 86400000,
  },
  {
    id: "ann-3",
    title: "Attendance Policy Update",
    body: "A reminder that students with more than 5 unexcused absences will require a parent conference before returning to class. Please review the updated policy on the school website.",
    authorId: "principal-1",
    authorName: "Dr. Kim Wells",
    authorRole: "principal",
    targetRoles: ["parent", "student"],
    priority: "important",
    createdAt: Date.now() - 5 * 86400000,
  },
];

export const _DEMO_PARENT_CHILDREN = [
  {
    studentId: "s1",
    name: "Emma Garcia",
    grade: 10,
    gpa: 3.1,
    attendanceRate: 91.3,
    standing: "On track",
    recentGrades: [
      {
        courseName: "Algebra II",
        assignment: "Algebra Quiz 1",
        grade: 82,
        earnedPoints: 41,
        totalPoints: 50,
        date: Date.now() - 7 * 86400000,
      },
      {
        courseName: "Pre-Calculus",
        assignment: "Short Story Analysis",
        grade: 92,
        earnedPoints: 46,
        totalPoints: 50,
        date: Date.now() - 5 * 86400000,
      },
      {
        courseName: "Biology Honors",
        assignment: "Lab Report",
        grade: 70,
        earnedPoints: 42,
        totalPoints: 60,
        date: Date.now() - 2 * 86400000,
      },
    ],
    recentAttendance: {
      status: "absent",
      date: Date.now() - 1 * 86400000,
      course: "Algebra II",
    },
    unreadMessageCount: 1,
    pendingSlips: 0,
    upcomingConferences: [],
  },
  {
    studentId: "s2",
    name: "Miguel Garcia",
    grade: 11,
    gpa: 3.6,
    attendanceRate: 96.0,
    standing: "Doing well",
    recentGrades: [
      {
        courseName: "Physics",
        assignment: "Chapter 4 Test",
        grade: 91,
        earnedPoints: 91,
        totalPoints: 100,
        date: Date.now() - 4 * 86400000,
      },
    ],
    recentAttendance: null,
    unreadMessageCount: 0,
    pendingSlips: 1,
    upcomingConferences: [
      { date: Date.now() + 5 * 86400000, teacher: "Mr. Davis" },
    ],
  },
];

export const DEMO_SCHEDULE: ScheduleEntry[] = [
  {
    day: 1,
    period: 1,
    courseId: "c1",
    room: "201",
    startTime: "7:45",
    endTime: "8:35",
  },
  {
    day: 1,
    period: 2,
    courseId: "c3",
    room: "115",
    startTime: "8:40",
    endTime: "9:30",
  },
  {
    day: 1,
    period: 3,
    courseId: "c2",
    room: "201",
    startTime: "9:35",
    endTime: "10:25",
  },
  {
    day: 1,
    period: 4,
    courseId: "c1",
    room: "201",
    startTime: "10:30",
    endTime: "11:20",
  },
  {
    day: 1,
    period: 5,
    courseId: "",
    room: "Cafeteria",
    startTime: "11:25",
    endTime: "12:15",
  },
  {
    day: 1,
    period: 6,
    courseId: "c3",
    room: "115",
    startTime: "12:20",
    endTime: "1:10",
  },
  {
    day: 1,
    period: 7,
    courseId: "c2",
    room: "201",
    startTime: "1:15",
    endTime: "2:05",
  },
  {
    day: 1,
    period: 8,
    courseId: "",
    room: "201",
    startTime: "2:10",
    endTime: "3:00",
  },
  {
    day: 2,
    period: 1,
    courseId: "c3",
    room: "115",
    startTime: "7:45",
    endTime: "8:35",
  },
  {
    day: 2,
    period: 2,
    courseId: "c1",
    room: "201",
    startTime: "8:40",
    endTime: "9:30",
  },
  {
    day: 2,
    period: 3,
    courseId: "c2",
    room: "201",
    startTime: "9:35",
    endTime: "10:25",
  },
  {
    day: 2,
    period: 4,
    courseId: "c3",
    room: "115",
    startTime: "10:30",
    endTime: "11:20",
  },
  {
    day: 2,
    period: 5,
    courseId: "",
    room: "Cafeteria",
    startTime: "11:25",
    endTime: "12:15",
  },
  {
    day: 2,
    period: 6,
    courseId: "c1",
    room: "201",
    startTime: "12:20",
    endTime: "1:10",
  },
  {
    day: 2,
    period: 7,
    courseId: "c2",
    room: "201",
    startTime: "1:15",
    endTime: "2:05",
  },
  {
    day: 2,
    period: 8,
    courseId: "",
    room: "201",
    startTime: "2:10",
    endTime: "3:00",
  },
  {
    day: 3,
    period: 1,
    courseId: "c2",
    room: "201",
    startTime: "7:45",
    endTime: "8:35",
  },
  {
    day: 3,
    period: 2,
    courseId: "c1",
    room: "201",
    startTime: "8:40",
    endTime: "9:30",
  },
  {
    day: 3,
    period: 3,
    courseId: "c3",
    room: "115",
    startTime: "9:35",
    endTime: "10:25",
  },
  {
    day: 3,
    period: 4,
    courseId: "c2",
    room: "201",
    startTime: "10:30",
    endTime: "11:20",
  },
  {
    day: 3,
    period: 5,
    courseId: "",
    room: "Cafeteria",
    startTime: "11:25",
    endTime: "12:15",
  },
  {
    day: 3,
    period: 6,
    courseId: "c1",
    room: "201",
    startTime: "12:20",
    endTime: "1:10",
  },
  {
    day: 3,
    period: 7,
    courseId: "c3",
    room: "115",
    startTime: "1:15",
    endTime: "2:05",
  },
  {
    day: 3,
    period: 8,
    courseId: "",
    room: "201",
    startTime: "2:10",
    endTime: "3:00",
  },
  {
    day: 4,
    period: 1,
    courseId: "c3",
    room: "115",
    startTime: "7:45",
    endTime: "8:35",
  },
  {
    day: 4,
    period: 2,
    courseId: "c2",
    room: "201",
    startTime: "8:40",
    endTime: "9:30",
  },
  {
    day: 4,
    period: 3,
    courseId: "c1",
    room: "201",
    startTime: "9:35",
    endTime: "10:25",
  },
  {
    day: 4,
    period: 4,
    courseId: "c3",
    room: "115",
    startTime: "10:30",
    endTime: "11:20",
  },
  {
    day: 4,
    period: 5,
    courseId: "",
    room: "Cafeteria",
    startTime: "11:25",
    endTime: "12:15",
  },
  {
    day: 4,
    period: 6,
    courseId: "c2",
    room: "201",
    startTime: "12:20",
    endTime: "1:10",
  },
  {
    day: 4,
    period: 7,
    courseId: "c1",
    room: "201",
    startTime: "1:15",
    endTime: "2:05",
  },
  {
    day: 4,
    period: 8,
    courseId: "",
    room: "201",
    startTime: "2:10",
    endTime: "3:00",
  },
  {
    day: 5,
    period: 1,
    courseId: "c1",
    room: "201",
    startTime: "7:45",
    endTime: "8:35",
  },
  {
    day: 5,
    period: 2,
    courseId: "c2",
    room: "201",
    startTime: "8:40",
    endTime: "9:30",
  },
  {
    day: 5,
    period: 3,
    courseId: "c3",
    room: "115",
    startTime: "9:35",
    endTime: "10:25",
  },
  {
    day: 5,
    period: 4,
    courseId: "c1",
    room: "201",
    startTime: "10:30",
    endTime: "11:20",
  },
  {
    day: 5,
    period: 5,
    courseId: "",
    room: "Cafeteria",
    startTime: "11:25",
    endTime: "12:15",
  },
  {
    day: 5,
    period: 6,
    courseId: "c3",
    room: "115",
    startTime: "12:20",
    endTime: "1:10",
  },
  {
    day: 5,
    period: 7,
    courseId: "c2",
    room: "201",
    startTime: "1:15",
    endTime: "2:05",
  },
  {
    day: 5,
    period: 8,
    courseId: "",
    room: "201",
    startTime: "2:10",
    endTime: "3:00",
  },
];

export const DEMO_STUDENT_GRADES: Record<
  string,
  {
    courseId: string;
    assignments: {
      assignmentId: string;
      score: number;
      maxPoints: number;
      weight: number;
      title: string;
      dueDate: string;
    }[];
  }[]
> = {
  s1: [
    {
      courseId: "c1",
      assignments: [
        {
          assignmentId: "a1",
          score: 92,
          maxPoints: 100,
          weight: 0.25,
          title: "Unit 4 Test",
          dueDate: "2026-05-15",
        },
        {
          assignmentId: "a3",
          score: 18,
          maxPoints: 20,
          weight: 0.05,
          title: "Problem Set 4.1",
          dueDate: "2026-05-20",
        },
        {
          assignmentId: "a1",
          score: 95,
          maxPoints: 100,
          weight: 0.25,
          title: "Unit 5 Test",
          dueDate: "2026-06-14",
        },
      ],
    },
    {
      courseId: "c3",
      assignments: [
        {
          assignmentId: "a2",
          score: 45,
          maxPoints: 50,
          weight: 0.15,
          title: "Lab Report — Diffusion",
          dueDate: "2026-05-10",
        },
        {
          assignmentId: "a5",
          score: 14,
          maxPoints: 15,
          weight: 0.05,
          title: "Cell Division Worksheet",
          dueDate: "2026-06-10",
        },
      ],
    },
  ],
  s2: [
    {
      courseId: "Algebra II",
      assignments: [
        {
          assignmentId: "a-s2-alg-1",
          score: 77,
          maxPoints: 100,
          weight: 0.25,
          title: "Unit 3 Test",
          dueDate: "2026-03-20",
        },
        {
          assignmentId: "a-s2-alg-2",
          score: 72,
          maxPoints: 100,
          weight: 0.25,
          title: "Unit 4 Test",
          dueDate: "2026-04-18",
        },
        {
          assignmentId: "a-s2-alg-3",
          score: 63,
          maxPoints: 100,
          weight: 0.25,
          title: "Unit 5 Test",
          dueDate: "2026-05-22",
        },
      ],
    },
    {
      courseId: "English 10",
      assignments: [
        {
          assignmentId: "a-s2-eng-1",
          score: 82,
          maxPoints: 100,
          weight: 0.25,
          title: "Essay 1 — Personal Narrative",
          dueDate: "2026-03-14",
        },
        {
          assignmentId: "a-s2-eng-2",
          score: 84,
          maxPoints: 100,
          weight: 0.25,
          title: "Essay 2 — Literary Analysis",
          dueDate: "2026-04-28",
        },
        {
          assignmentId: "a-s2-eng-3",
          score: 87,
          maxPoints: 100,
          weight: 0.25,
          title: "Research Paper Draft",
          dueDate: "2026-05-30",
        },
      ],
    },
    {
      courseId: "World History",
      assignments: [
        {
          assignmentId: "a-s2-hist-1",
          score: 88,
          maxPoints: 100,
          weight: 0.3,
          title: "Midterm Exam",
          dueDate: "2026-03-28",
        },
        {
          assignmentId: "a-s2-hist-2",
          score: 91,
          maxPoints: 100,
          weight: 0.3,
          title: "Primary Source Analysis",
          dueDate: "2026-05-08",
        },
      ],
    },
    {
      courseId: "Art Studio",
      assignments: [
        {
          assignmentId: "a-s2-art-1",
          score: 92,
          maxPoints: 100,
          weight: 0.35,
          title: "Portfolio Project 1",
          dueDate: "2026-04-05",
        },
        {
          assignmentId: "a-s2-art-2",
          score: 95,
          maxPoints: 100,
          weight: 0.35,
          title: "Portfolio Project 2",
          dueDate: "2026-05-19",
        },
      ],
    },
    {
      courseId: "PE / Health",
      assignments: [
        {
          assignmentId: "a-s2-pe-1",
          score: 95,
          maxPoints: 100,
          weight: 0.2,
          title: "Fitness Assessment",
          dueDate: "2026-04-10",
        },
        {
          assignmentId: "a-s2-pe-2",
          score: 98,
          maxPoints: 100,
          weight: 0.2,
          title: "Health Unit Quiz",
          dueDate: "2026-05-27",
        },
      ],
    },
  ],
  s4: [
    {
      courseId: "c3",
      assignments: [
        {
          assignmentId: "a2",
          score: 49,
          maxPoints: 50,
          weight: 0.15,
          title: "Lab Report — Diffusion",
          dueDate: "2026-05-10",
        },
        {
          assignmentId: "a5",
          score: 15,
          maxPoints: 15,
          weight: 0.05,
          title: "Cell Division Worksheet",
          dueDate: "2026-06-10",
        },
      ],
    },
  ],
};

export const DEMO_ATTENDANCE_RECORDS: Record<string, AttendanceRecord[]> = {
  s1: [
    {
      id: "att-s1-1",
      studentId: "s1",
      date: "2026-06-02",
      status: "present",
      recordedBy: "staff-1",
    },
    {
      id: "att-s1-2",
      studentId: "s1",
      date: "2026-06-03",
      status: "present",
      recordedBy: "staff-1",
    },
    {
      id: "att-s1-3",
      studentId: "s1",
      date: "2026-06-04",
      status: "tardy",
      recordedBy: "staff-1",
    },
    {
      id: "att-s1-4",
      studentId: "s1",
      date: "2026-06-05",
      status: "present",
      recordedBy: "staff-1",
    },
    {
      id: "att-s1-5",
      studentId: "s1",
      date: "2026-06-08",
      status: "present",
      recordedBy: "staff-1",
    },
    {
      id: "att-s1-6",
      studentId: "s1",
      date: "2026-06-09",
      status: "present",
      recordedBy: "staff-1",
    },
    {
      id: "att-s1-7",
      studentId: "s1",
      date: "2026-06-10",
      status: "present",
      recordedBy: "staff-1",
    },
    {
      id: "att-s1-8",
      studentId: "s1",
      date: "2026-06-11",
      status: "present",
      recordedBy: "staff-1",
    },
    {
      id: "att-s1-9",
      studentId: "s1",
      date: "2026-06-12",
      status: "absent",
      recordedBy: "staff-1",
    },
    {
      id: "att-s1-10",
      studentId: "s1",
      date: "2026-05-28",
      status: "present",
      recordedBy: "staff-1",
    },
    {
      id: "att-s1-11",
      studentId: "s1",
      date: "2026-05-29",
      status: "present",
      recordedBy: "staff-1",
    },
    {
      id: "att-s1-12",
      studentId: "s1",
      date: "2026-05-30",
      status: "present",
      recordedBy: "staff-1",
    },
  ],
  s2: [
    {
      id: "att-s2-1",
      studentId: "s2",
      date: "2026-03-04",
      status: "present",
      recordedBy: "staff-1",
    },
    {
      id: "att-s2-2",
      studentId: "s2",
      date: "2026-03-05",
      status: "absent",
      recordedBy: "staff-1",
      notes: "Unexcused",
    },
    {
      id: "att-s2-3",
      studentId: "s2",
      date: "2026-03-06",
      status: "present",
      recordedBy: "staff-1",
    },
    {
      id: "att-s2-4",
      studentId: "s2",
      date: "2026-03-11",
      status: "present",
      recordedBy: "staff-1",
    },
    {
      id: "att-s2-5",
      studentId: "s2",
      date: "2026-03-18",
      status: "absent",
      recordedBy: "staff-1",
      notes: "Unexcused",
    },
    {
      id: "att-s2-6",
      studentId: "s2",
      date: "2026-03-19",
      status: "present",
      recordedBy: "staff-1",
    },
    {
      id: "att-s2-7",
      studentId: "s2",
      date: "2026-03-25",
      status: "excused",
      recordedBy: "staff-1",
      notes: "Medical appointment",
    },
    {
      id: "att-s2-8",
      studentId: "s2",
      date: "2026-04-01",
      status: "present",
      recordedBy: "staff-1",
    },
    {
      id: "att-s2-9",
      studentId: "s2",
      date: "2026-04-08",
      status: "absent",
      recordedBy: "staff-1",
      notes: "Unexcused",
    },
    {
      id: "att-s2-10",
      studentId: "s2",
      date: "2026-04-09",
      status: "present",
      recordedBy: "staff-1",
    },
    {
      id: "att-s2-11",
      studentId: "s2",
      date: "2026-04-15",
      status: "present",
      recordedBy: "staff-1",
    },
    {
      id: "att-s2-12",
      studentId: "s2",
      date: "2026-04-22",
      status: "absent",
      recordedBy: "staff-1",
      notes: "Unexcused",
    },
    {
      id: "att-s2-13",
      studentId: "s2",
      date: "2026-04-29",
      status: "excused",
      recordedBy: "staff-1",
      notes: "Family obligation",
    },
    {
      id: "att-s2-14",
      studentId: "s2",
      date: "2026-05-06",
      status: "present",
      recordedBy: "staff-1",
    },
    {
      id: "att-s2-15",
      studentId: "s2",
      date: "2026-05-13",
      status: "absent",
      recordedBy: "staff-1",
      notes: "Unexcused",
    },
    {
      id: "att-s2-16",
      studentId: "s2",
      date: "2026-05-20",
      status: "present",
      recordedBy: "staff-1",
    },
    {
      id: "att-s2-17",
      studentId: "s2",
      date: "2026-05-27",
      status: "absent",
      recordedBy: "staff-1",
      notes: "Unexcused",
    },
    {
      id: "att-s2-18",
      studentId: "s2",
      date: "2026-06-03",
      status: "present",
      recordedBy: "staff-1",
    },
    {
      id: "att-s2-19",
      studentId: "s2",
      date: "2026-06-10",
      status: "excused",
      recordedBy: "staff-1",
      notes: "Medical",
    },
    {
      id: "att-s2-20",
      studentId: "s2",
      date: "2026-06-11",
      status: "absent",
      recordedBy: "staff-1",
      notes: "Unexcused",
    },
  ],
  s4: [
    {
      id: "att-s4-1",
      studentId: "s4",
      date: "2026-06-02",
      status: "present",
      recordedBy: "staff-4",
    },
    {
      id: "att-s4-2",
      studentId: "s4",
      date: "2026-06-03",
      status: "present",
      recordedBy: "staff-4",
    },
    {
      id: "att-s4-3",
      studentId: "s4",
      date: "2026-06-04",
      status: "present",
      recordedBy: "staff-4",
    },
    {
      id: "att-s4-4",
      studentId: "s4",
      date: "2026-06-05",
      status: "present",
      recordedBy: "staff-4",
    },
    {
      id: "att-s4-5",
      studentId: "s4",
      date: "2026-06-08",
      status: "present",
      recordedBy: "staff-4",
    },
    {
      id: "att-s4-6",
      studentId: "s4",
      date: "2026-06-09",
      status: "present",
      recordedBy: "staff-4",
    },
    {
      id: "att-s4-7",
      studentId: "s4",
      date: "2026-06-10",
      status: "present",
      recordedBy: "staff-4",
    },
    {
      id: "att-s4-8",
      studentId: "s4",
      date: "2026-06-11",
      status: "present",
      recordedBy: "staff-4",
    },
    {
      id: "att-s4-9",
      studentId: "s4",
      date: "2026-06-12",
      status: "present",
      recordedBy: "staff-4",
    },
    {
      id: "att-s4-10",
      studentId: "s4",
      date: "2026-05-28",
      status: "present",
      recordedBy: "staff-4",
    },
    {
      id: "att-s4-11",
      studentId: "s4",
      date: "2026-05-29",
      status: "present",
      recordedBy: "staff-4",
    },
    {
      id: "att-s4-12",
      studentId: "s4",
      date: "2026-05-30",
      status: "present",
      recordedBy: "staff-4",
    },
  ],
};

export const DEMO_MORNING_PICTURE: MorningPicture = {
  date: new Date().toISOString(),
  headline: "Calm morning — two items worth your attention.",
  deltas: [
    {
      category: "Attendance",
      description:
        "Grade 10 attendance dipped to 88% yesterday — down from 93% week prior.",
      urgency: "medium",
    },
    {
      category: "Behaviour",
      description:
        "One new incident logged after school: Tyler Reyes, minor, routed to counsellor.",
      urgency: "low",
    },
  ],
  workingWell: [
    "Grade 11 GPA average up 0.2 points this term.",
    "Parent conference booking rate at 94% — highest this year.",
  ],
  needsDecision: ["IEP renewal for Maya Okonkwo is due in 9 days."],
  nothingChanged: false,
};
