/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.1.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'displayName' : string,
  'userId' : bigint,
  'role' : Role,
  'principalText' : string,
  'isOwner' : boolean,
}
export interface Activity {
  'id' : ActivityId,
  'eligibilityGpaMin' : number,
  'name' : string,
  'actType' : { 'fineArts' : null } |
    { 'club' : null } |
    { 'sport' : null } |
    { 'serviceHours' : null },
  'season' : [] | [string],
  'eligibilityAttendanceMin' : number,
  'coachAdvisorId' : [] | [string],
  'maxRoster' : [] | [bigint],
}
export type ActivityId = bigint;
export interface ActivityRoster {
  'status' : { 'active' : null } |
    { 'inactive' : null } |
    { 'waitlisted' : null },
  'studentId' : string,
  'joinedAt' : bigint,
  'role' : { 'member' : null } |
    { 'leader' : null } |
    { 'captain' : null },
  'activityId' : ActivityId,
}
export interface Announcement {
  'id' : AnnouncementId,
  'title' : string,
  'authorId' : StaffId,
  'body' : string,
  'createdAt' : Timestamp,
  'targetRoles' : Array<Role>,
  'priority' : AnnouncementPriority,
  'isDemoData' : boolean,
}
export type AnnouncementId = bigint;
export type AnnouncementPriority = { 'info' : null } |
  { 'important' : null } |
  { 'urgent' : null };
export interface Appointment {
  'id' : AppointmentId,
  'status' : AppointmentStatus,
  'studentId' : StudentId,
  'createdAt' : Timestamp,
  'appointmentType' : AppointmentType,
  'counsellorId' : StaffId,
  'notes' : string,
  'dateTime' : Timestamp,
  'isDemoData' : boolean,
}
export type AppointmentId = bigint;
export type AppointmentStatus = { 'scheduled' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export type AppointmentType = { 'groupSession' : null } |
  { 'checkIn' : null } |
  { 'custom' : null } |
  { 'intervention' : null } |
  { 'referralFollowUp' : null } |
  { 'parentConference' : null };
export interface Assignment {
  'id' : AssignmentId,
  'weight' : number,
  'assignmentType' : AssignmentType,
  'name' : string,
  'term' : string,
  'dueDate' : Timestamp,
  'description' : [] | [string],
  'isHighStakes' : boolean,
  'courseId' : CourseId,
  'isDemoData' : boolean,
  'points' : number,
  'linkedLessonId' : [] | [LessonId],
}
export type AssignmentId = bigint;
export type AssignmentType = { 'quiz' : null } |
  { 'test' : null } |
  { 'homework' : null } |
  { 'essay' : null } |
  { 'project' : null };
export interface AssignmentV2 {
  'id' : AssignmentId,
  'categoryId' : CategoryId,
  'pointsPossible' : bigint,
  'name' : string,
  'dueDate' : [] | [string],
  'classId' : CourseId,
}
export interface AssignmentWithStatus {
  'earnedPoints' : [] | [number],
  'assignment' : Assignment,
  'submissionStatus' : SubmissionStatus,
}
export type AttendanceId = bigint;
export interface AttendancePattern {
  'trend' : AttendanceTrend,
  'studentId' : StudentId,
  'attendanceRate' : number,
  'thresholdFlag' : boolean,
  'chronicAbsenceFlag' : boolean,
  'lastFiveEntries' : Array<AttendanceRecord__1>,
}
export interface AttendancePattern__1 {
  'trend' : string,
  'studentId' : StudentId,
  'chronicAbsence' : boolean,
  'presentDays' : bigint,
  'totalDays' : bigint,
  'excusedDays' : bigint,
  'tardyDays' : bigint,
  'absentDays' : bigint,
  'belowThreshold' : boolean,
  'percentage' : number,
}
export interface AttendanceRecord {
  'id' : AttendanceId,
  'status' : AttendanceStatus,
  'studentId' : StudentId,
  'period' : [] | [string],
  'date' : string,
  'markedBy' : StaffId,
  'courseId' : CourseId,
  'isDemoData' : boolean,
}
export interface AttendanceRecord__1 {
  'id' : AttendanceId,
  'status' : AttendanceStatus__1,
  'studentId' : StudentId,
  'date' : string,
  'classId' : [] | [string],
  'notes' : [] | [string],
  'isDemoData' : boolean,
  'enteredAt' : bigint,
  'enteredBy' : string,
}
export type AttendanceStatus = { 'tardy' : null } |
  { 'present' : null } |
  { 'absent' : null } |
  { 'excused' : null };
export type AttendanceStatus__1 = { 'Present' : null } |
  { 'Excused' : null } |
  { 'Tardy' : null } |
  { 'Absent' : null };
export interface AttendanceSummary {
  'tardy' : bigint,
  'present' : bigint,
  'rate' : number,
  'absent' : bigint,
}
export type AttendanceTrend = { 'Flat' : null } |
  { 'Improving' : null } |
  { 'Declining' : null };
export interface AuditEntry {
  'id' : AuditId,
  'action' : string,
  'newValue' : [] | [string],
  'previousValue' : [] | [string],
  'entityId' : bigint,
  'performedAt' : Timestamp,
  'performedBy' : StaffId,
  'entityType' : string,
}
export interface AuditEntry__1 {
  'id' : AuditId,
  'action' : string,
  'actorRole' : Role,
  'actorId' : string,
  'entityId' : string,
  'timestamp' : bigint,
  'entityType' : string,
  'delta' : [] | [string],
}
export type AuditId = bigint;
export interface BehaviourSummary {
  'incidents' : bigint,
  'followUpsComplete' : bigint,
}
export interface BoardItem {
  'id' : BoardItemId,
  'title' : string,
  'content' : string,
  'channelId' : [] | [ChannelId],
  'createdAt' : bigint,
  'createdBy' : string,
  'pinnedAt' : [] | [bigint],
  'pinnedBy' : [] | [string],
  'isPinned' : boolean,
}
export type BoardItemId = bigint;
export interface CaseloadEntry {
  'student' : CaseloadStudent,
  'upcomingCommitments' : Array<Commitment>,
  'interventions' : Array<Intervention>,
}
export interface CaseloadStudent {
  'specialPopFlags' : {
    'ell' : boolean,
    'medicalAlert' : [] | [string],
    'sped' : boolean,
  },
  'studentId' : StudentId,
  'gradeTrajectory' : string,
  'recentIncidents' : bigint,
  'openCommitments' : bigint,
  'name' : string,
  'hasActiveIntervention' : boolean,
  'attendancePct' : number,
  'grade' : bigint,
}
export interface CaseloadSummary {
  'studentsWithAttendanceConcerns' : bigint,
  'openCommitments' : bigint,
  'studentsWithGradeConcerns' : bigint,
  'totalStudents' : bigint,
  'dueThisWeek' : bigint,
  'overdueRenewals' : bigint,
}
export type CategoryId = string;
export interface Channel {
  'id' : ChannelId,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'description' : [] | [string],
  'isArchived' : boolean,
  'scopedRoles' : Array<string>,
  'isRoleScoped' : boolean,
}
export type ChannelId = bigint;
export interface ChannelMessage {
  'id' : ChannelMsgId,
  'content' : string,
  'channelId' : ChannelId,
  'authorId' : string,
  'sentAt' : bigint,
  'mentionedUsers' : Array<string>,
  'parentId' : [] | [ChannelMsgId],
  'editedAt' : [] | [bigint],
  'isPinned' : boolean,
}
export type ChannelMsgId = bigint;
export interface ClassGradebookEntry {
  'grades' : Array<
    {
      'weight' : number,
      'maxScore' : number,
      'assignmentName' : string,
      'score' : [] | [number],
      'assignmentId' : AssignmentId,
    }
  >,
  'studentId' : StudentId,
  'studentName' : string,
  'average' : number,
}
export interface ClassMeeting {
  'id' : MeetingId,
  'period' : bigint,
  'dayOfWeek' : bigint,
  'room' : string,
  'term' : string,
  'teacherId' : StaffId,
  'courseId' : CourseId,
  'isDemoData' : boolean,
}
export interface ClassReport {
  'topStudents' : Array<StudentGradeSummary>,
  'classAverage' : number,
  'term' : string,
  'totalStudents' : bigint,
  'teacherName' : string,
  'roster' : Array<StudentGradeSummary>,
  'courseName' : string,
  'courseId' : CourseId,
  'strugglingStudents' : Array<StudentGradeSummary>,
}
export interface CoTeacherClassRow {
  'classId' : string,
  'coTeacher' : string,
  'leadTeacher' : string,
  'className' : string,
  'studentCount' : bigint,
}
export interface Commitment {
  'id' : CommitmentId,
  'status' : CommitmentStatus,
  'completedAt' : [] | [Timestamp],
  'studentId' : StudentId,
  'ownerId' : StaffId,
  'createdAt' : Timestamp,
  'dueDate' : Timestamp,
  'description' : string,
  'transitionLog' : Array<CommitmentTransitionEvent>,
  'commitmentType' : CommitmentType,
  'notes' : string,
  'isDemoData' : boolean,
}
export type CommitmentId = bigint;
export type CommitmentStatus = { 'cancelled' : null } |
  { 'open' : null } |
  { 'completed' : null } |
  { 'overdue' : null } |
  { 'inProgress' : null };
export interface CommitmentSurfacing {
  'thisWeek' : Array<Commitment>,
  'dueToday' : Array<Commitment>,
  'overdue' : Array<Commitment>,
  'comingSoon' : Array<Commitment>,
}
export interface CommitmentTransitionEvent {
  'toStatus' : CommitmentStatus,
  'note' : string,
  'fromStatus' : CommitmentStatus,
  'actorId' : StaffId,
  'timestamp' : Timestamp,
}
export type CommitmentType = { 'behaviourFollowUp' : null } |
  { 'permissionSlip' : null } |
  { 'custom' : null } |
  { 'conferenceBooking' : null } |
  { 'iepRenewal' : null } |
  { 'counsellorFollowUp' : null } |
  { 'parentCall' : null } |
  { 'workHome' : null };
export interface ComplianceItem {
  'id' : ComplianceItemId,
  'status' : ComplianceStatus,
  'completedAt' : [] | [Timestamp],
  'studentId' : StudentId,
  'ownerId' : StaffId,
  'dueDate' : Timestamp,
  'notes' : [] | [string],
  'itemType' : ComplianceItemType,
  'isDemoData' : boolean,
}
export type ComplianceItemId = bigint;
export type ComplianceItemType = { 'progressReport' : null } |
  { 'triennial' : null } |
  { 'iepMeeting' : null } |
  { 'annualReview' : null };
export type ComplianceStatus = { 'pending' : null } |
  { 'complete' : null } |
  { 'overdue' : null };
export interface ConferenceBooking {
  'id' : ConferenceBookingId,
  'status' : { 'cancelled' : null } |
    { 'rescheduled' : null } |
    { 'confirmed' : null },
  'studentId' : string,
  'bookedAt' : bigint,
  'notificationSent' : boolean,
  'slotId' : ConferenceSlotId,
  'teacherId' : string,
  'parentId' : string,
  'isDemoData' : boolean,
}
export type ConferenceBookingId = bigint;
export interface ConferenceSlot {
  'id' : ConferenceSlotId,
  'status' : { 'cancelled' : null } |
    { 'booked' : null } |
    { 'available' : null },
  'studentId' : string,
  'bookedBy' : [] | [string],
  'durationMinutes' : bigint,
  'notes' : [] | [string],
  'teacherId' : string,
  'parentId' : string,
  'dateTime' : bigint,
  'isDemoData' : boolean,
}
export type ConferenceSlotId = bigint;
export interface Course {
  'id' : CourseId,
  'code' : string,
  'name' : string,
  'coTeacherId' : [] | [StaffId],
  'grade' : bigint,
  'teacherId' : StaffId,
  'units' : Array<Unit>,
  'department' : string,
  'isDemoData' : boolean,
}
export type CourseId = bigint;
export interface CourseSummary {
  'teacherComment' : string,
  'courseName' : string,
  'finalGrade' : number,
  'courseId' : CourseId,
  'letterGrade' : string,
}
export interface CurriculumCourseRow {
  'assignmentCount' : bigint,
  'unitCount' : bigint,
  'lessonCount' : bigint,
  'courseName' : string,
  'courseId' : string,
}
export interface DecisionItem {
  'title' : string,
  'urgency' : SignalUrgency,
  'description' : string,
}
export interface Demographics {
  'frl' : boolean,
  'race' : [] | [string],
  'districtCode' : [] | [string],
  'ethnicity' : [] | [string],
}
export interface DistrictHealthSummary {
  'attendanceRate' : number,
  'averageGPA' : number,
  'incidentCount' : bigint,
  'staffCount' : bigint,
  'enrollmentCount' : bigint,
  'schoolName' : string,
}
export interface Enrollment {
  'studentId' : StudentId,
  'term' : string,
  'courseId' : CourseId,
  'isDemoData' : boolean,
}
export type EnrollmentStatus = { 'active' : null } |
  { 'transferred' : null } |
  { 'graduated' : null } |
  { 'withdrawn' : null };
export interface FieldTrip {
  'id' : FieldTripId,
  'destination' : string,
  'cost' : [] | [number],
  'date' : bigint,
  'name' : string,
  'activityId' : [] | [ActivityId],
  'approvalStatus' : { 'cancelled' : null } |
    { 'pending' : null } |
    { 'approved' : null },
  'permissionSlipRequired' : boolean,
}
export type FieldTripId = bigint;
export interface Grade {
  'id' : GradeId,
  'weight' : number,
  'studentId' : StudentId,
  'gradedAt' : Timestamp,
  'gradedBy' : StaffId,
  'value' : number,
  'term' : string,
  'auditLog' : Array<AuditEntry>,
  'isHighStakes' : boolean,
  'assignmentId' : AssignmentId,
  'courseId' : CourseId,
  'isDemoData' : boolean,
}
export interface GradeCategory {
  'id' : CategoryId,
  'weight' : bigint,
  'name' : string,
  'classId' : CourseId,
}
export type GradeId = bigint;
export interface Guardian {
  'isEmergency' : boolean,
  'homeLanguage' : string,
  'relationship' : string,
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export interface HandoffLogEntry {
  'action' : string,
  'oldValue' : [] | [string],
  'studentName' : string,
  'newValue' : string,
  'gradeId' : string,
  'teacherName' : string,
  'teacherId' : string,
  'timestamp' : bigint,
}
export interface IEPAccommodation {
  'description' : string,
  'category' : string,
}
export interface IEPDetail { 'notes' : Array<IEPNote>, 'record' : IEPRecord }
export interface IEPGoal {
  'id' : bigint,
  'domain' : string,
  'description' : string,
  'progress' : string,
  'targetDate' : [] | [Timestamp],
}
export interface IEPNote {
  'id' : IEPNoteId,
  'studentId' : StudentId,
  'authorId' : StaffId,
  'body' : string,
  'createdAt' : Timestamp,
  'noteType' : IEPNoteType,
  'isDemoData' : boolean,
}
export type IEPNoteId = bigint;
export type IEPNoteType = { 'service' : null } |
  { 'review' : null } |
  { 'goal' : null } |
  { 'accommodation' : null } |
  { 'meeting' : null } |
  { 'general' : null };
export interface IEPRecord {
  'studentId' : StudentId,
  'reviewHistory' : Array<IEPReviewEntry>,
  'lastUpdatedAt' : Timestamp,
  'lastUpdatedBy' : StaffId,
  'goals' : Array<IEPGoal>,
  'accommodations' : Array<IEPAccommodation>,
  'services' : Array<IEPService>,
  'isDemoData' : boolean,
  'renewalDate' : Timestamp,
}
export interface IEPReviewEntry {
  'reviewedAt' : Timestamp,
  'reviewedBy' : StaffId,
  'notes' : string,
}
export interface IEPService {
  'serviceType' : string,
  'provider' : string,
  'endDate' : [] | [Timestamp],
  'minutesPerWeek' : bigint,
  'startDate' : Timestamp,
}
export interface IEPStudent {
  'studentId' : StudentId,
  'name' : string,
  'urgencyTier' : { 'warning' : null } |
    { 'danger' : null } |
    { 'info' : null } |
    { 'future' : null } |
    { 'overdue' : null },
  'grade' : bigint,
  'spedFlags' : SpecialPopFlags,
  'daysToRenewal' : bigint,
  'contextualNextStep' : string,
  'renewalDate' : Timestamp,
}
export interface Incident {
  'id' : IncidentId,
  'status' : IncidentStatus,
  'studentId' : StudentId,
  'createdAt' : Timestamp,
  'commitmentId' : [] | [CommitmentId],
  'routedTo' : [] | [StaffId],
  'description' : string,
  'reportedBy' : StaffId,
  'severity' : IncidentSeverity,
  'isDemoData' : boolean,
  'timeline' : Array<IncidentEvent>,
}
export interface IncidentEvent {
  'status' : IncidentStatus,
  'staffId' : StaffId,
  'note' : string,
  'occurredAt' : Timestamp,
}
export type IncidentId = bigint;
export interface IncidentPattern {
  'trend' : IncidentTrend,
  'studentId' : StudentId,
  'severityBreakdown' : Array<[bigint, bigint]>,
  'count90day' : bigint,
  'repeatPatternFlag' : boolean,
  'escalationTimelineDays' : [] | [bigint],
}
export type IncidentSeverity = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export type IncidentStatus = { 'closed' : null } |
  { 'reviewing' : null } |
  { 'logged' : null } |
  { 'followUp' : null } |
  { 'routed' : null };
export type IncidentTrend = { 'Flat' : null } |
  { 'Decreasing' : null } |
  { 'Increasing' : null };
export interface Intervention {
  'id' : InterventionId,
  'status' : InterventionStatus,
  'studentId' : StudentId,
  'createdAt' : Timestamp,
  'commitmentId' : [] | [CommitmentId],
  'description' : string,
  'finalOutcome' : [] | [string],
  'outcomes' : Array<InterventionOutcome>,
  'planDetails' : string,
  'interventionType' : InterventionType,
  'counsellorId' : StaffId,
  'isDemoData' : boolean,
  'followUpDate' : Timestamp,
}
export type InterventionId = bigint;
export interface InterventionOutcome {
  'recordedAt' : Timestamp,
  'notes' : string,
  'outcome' : string,
}
export type InterventionStatus = { 'closed' : null } |
  { 'active' : null } |
  { 'completed' : null };
export type InterventionType = { 'custom' : null } |
  { 'academic' : null } |
  { 'attendance' : null } |
  { 'socialEmotional' : null } |
  { 'family' : null } |
  { 'behavioural' : null };
export interface Lesson {
  'id' : LessonId,
  'name' : string,
  'description' : string,
  'unitId' : UnitId,
  'orderIndex' : bigint,
}
export type LessonId = bigint;
export type MeetingId = bigint;
export interface Message {
  'id' : MessageId,
  'subject' : string,
  'body' : string,
  'toId' : StaffId,
  'isRead' : boolean,
  'sentAt' : Timestamp,
  'fromId' : StaffId,
  'threadId' : ThreadId,
  'isDemoData' : boolean,
}
export type MessageId = bigint;
export interface MorningPicture {
  'generatedAt' : Timestamp,
  'headline' : string,
  'whatsWorking' : Array<string>,
  'urgentStudents' : Array<UrgentStudent>,
  'needsDecision' : Array<DecisionItem>,
  'overnightDeltas' : Array<OvernightDelta>,
}
export interface Notification {
  'id' : NotificationId,
  'title' : string,
  'body' : string,
  'createdAt' : Timestamp,
  'tier' : NotificationTier,
  'isRead' : boolean,
  'relatedId' : [] | [bigint],
  'isDemoData' : boolean,
  'recipientId' : StaffId,
  'relatedType' : [] | [string],
  'eventType' : NotificationEventType,
}
export type NotificationEventType = { 'conferenceBooked' : null } |
  { 'attendanceFlagged' : null } |
  { 'riskSignal' : null } |
  { 'behaviourFollowUp' : null } |
  { 'other' : null } |
  { 'assignmentSubmitted' : null } |
  { 'messageReceived' : null } |
  { 'announcementPosted' : null } |
  { 'gradePosted' : null } |
  { 'commitmentDue' : null } |
  { 'iepDue' : null } |
  { 'incidentRouted' : null };
export type NotificationId = bigint;
export type NotificationTier = { 'important' : null } |
  { 'critical' : null } |
  { 'informational' : null };
export interface OverloadFlag {
  'week' : string,
  'affectedStudentIds' : Array<string>,
  'courseId' : string,
  'assignmentIds' : Array<string>,
  'reason' : string,
}
export interface OvernightDelta {
  'metric' : string,
  'previous' : number,
  'change' : string,
  'current' : number,
}
export interface PaginatedStudents {
  'total' : bigint,
  'students' : Array<Student>,
}
export interface PermissionSlip {
  'id' : PermissionSlipId,
  'status' : { 'costBarrier' : null } |
    { 'signed' : null } |
    { 'unsigned' : null } |
    { 'declined' : null },
  'studentId' : string,
  'tripId' : FieldTripId,
  'signedAt' : [] | [bigint],
  'signedBy' : [] | [string],
}
export type PermissionSlipId = bigint;
export interface ReportCard {
  'studentId' : StudentId,
  'behaviourSummary' : BehaviourSummary,
  'attendanceSummary' : AttendanceSummary,
  'termId' : string,
  'courseSummaries' : Array<CourseSummary>,
}
export interface ReportCardData {
  'gpa' : number,
  'term' : string,
  'courseGrades' : Array<[Course, number]>,
  'student' : Student,
  'attendanceSummary' : AttendancePattern__1,
}
export type Role = { 'principal' : null } |
  { 'departmentHead' : null } |
  { 'curriculumCoordinator' : null } |
  { 'spedCoordinator' : null } |
  { 'counsellor' : null } |
  { 'teacher' : null } |
  { 'substitute' : null } |
  { 'coTeacher' : null } |
  { 'schoolAdmin' : null } |
  { 'student' : null } |
  { 'districtAdmin' : null } |
  { 'parent' : null };
export interface RoleContext { 'userId' : StaffId, 'role' : Role }
export interface Score {
  'id' : ScoreId,
  'studentId' : StudentId,
  'pointsEarned' : [] | [bigint],
  'assignmentId' : AssignmentId,
}
export type ScoreId = string;
export type ServiceEntryId = bigint;
export interface ServiceHoursEntry {
  'id' : ServiceEntryId,
  'studentId' : string,
  'hours' : number,
  'approvedBy' : [] | [string],
  'activityId' : [] | [ActivityId],
  'description' : string,
  'loggedAt' : bigint,
}
export interface SignalCard {
  'id' : SignalId,
  'studentId' : [] | [StudentId],
  'studentName' : [] | [string],
  'urgency' : SignalUrgency,
  'createdAt' : Timestamp,
  'signalType' : SignalType,
  'reason' : string,
}
export type SignalId = bigint;
export type SignalType = { 'pattern' : null } |
  { 'workload' : null } |
  { 'risk' : null } |
  { 'opportunity' : null } |
  { 'continuity' : null } |
  { 'celebration' : null } |
  { 'commitment' : null };
export type SignalUrgency = { 'info' : null } |
  { 'important' : null } |
  { 'critical' : null };
export interface SpecialPopFlags {
  'ell' : boolean,
  'medicalAlert' : [] | [string],
  'sped' : boolean,
  'wida' : [] | [string],
  'mcKinneyVento' : boolean,
  'gifted' : boolean,
  'fosterYouth' : boolean,
}
export interface SpecialPopFlags__1 {
  'medicalAlerts' : Array<string>,
  'isGifted' : boolean,
  'isMcKinneyVento' : boolean,
  'iepStartDate' : [] | [bigint],
  'widaLevel' : [] | [bigint],
  'isELL' : boolean,
  'isIEP' : boolean,
  'isFosterYouth' : boolean,
  'iepRenewalDate' : [] | [bigint],
}
export interface Staff {
  'id' : StaffId,
  'departments' : Array<string>,
  'name' : string,
  'role' : Role,
  'email' : string,
  'assignedClasses' : Array<CourseId>,
  'isDemoData' : boolean,
}
export type StaffId = bigint;
export interface Student {
  'id' : StudentId,
  'dob' : string,
  'specialPopFlags' : SpecialPopFlags,
  'guardians' : Array<Guardian>,
  'name' : string,
  'homeroom' : string,
  'enrollmentStatus' : EnrollmentStatus,
  'counsellorId' : [] | [StaffId],
  'grade' : bigint,
  'preferredName' : [] | [string],
  'spedCoordinatorId' : [] | [StaffId],
  'photo' : [] | [string],
  'isDemoData' : boolean,
}
export interface StudentContact {
  'homeLanguage' : [] | [string],
  'relationship' : string,
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
  'emergencyPriority' : bigint,
}
export interface StudentFullRecord {
  'signals' : Array<UnderstandingSignal>,
  'attendanceRate' : number,
  'trajectory' : Array<TrajectoryResult__1>,
  'student' : Student__1,
  'auditTrail' : Array<AuditEntry__1>,
  'currentGPA' : [] | [number],
  'commitments' : Array<Commitment>,
  'behaviourPatternFlag' : boolean,
}
export interface StudentGradeSummary {
  'studentId' : StudentId,
  'studentName' : string,
  'letterGrade' : string,
  'weightedAvg' : number,
}
export interface StudentGradeView {
  'weight' : number,
  'assignmentName' : string,
  'term' : string,
  'score' : number,
  'courseName' : string,
  'courseId' : CourseId,
  'letterGrade' : string,
}
export interface StudentGradebookClassSummary {
  'classId' : CourseId,
  'weightedPercentage' : number,
  'className' : string,
  'letterGrade' : string,
}
export type StudentId = bigint;
export interface StudentRosterRow {
  'gpa' : [] | [number],
  'attendanceRate' : number,
  'student' : Student,
}
export interface StudentSummary {
  'studentId' : StudentId,
  'name' : string,
  'courseIds' : Array<CourseId>,
  'grade' : bigint,
}
export interface StudentTranscript {
  'terms' : Array<TranscriptTerm__1>,
  'studentId' : StudentId,
  'studentName' : string,
  'cumulativeGpa' : number,
  'totalCredits' : number,
}
export interface StudentWeightedResult {
  'studentId' : StudentId,
  'overallPercent' : number,
  'letterGrade' : string,
}
export interface Student__1 {
  'id' : StudentId,
  'dob' : [] | [string],
  'enrolmentStatus' : { 'Inactive' : null } |
    { 'Active' : null } |
    { 'Transferred' : null },
  'contacts' : Array<StudentContact>,
  'enrolmentDate' : bigint,
  'assignedSpedId' : [] | [string],
  'code' : string,
  'name' : string,
  'homeroom' : [] | [string],
  'specialPop' : SpecialPopFlags__1,
  'grade' : bigint,
  'assignedCounsellorId' : [] | [string],
  'preferredName' : [] | [string],
  'photo' : [] | [string],
  'isDemoData' : boolean,
  'demographics' : Demographics,
}
export interface Submission {
  'id' : SubmissionId,
  'earnedPoints' : [] | [number],
  'status' : SubmissionStatus,
  'studentId' : StudentId,
  'submittedAt' : Timestamp,
  'assignmentId' : AssignmentId,
  'submissionText' : string,
  'isDemoData' : boolean,
}
export type SubmissionId = bigint;
export type SubmissionStatus = { 'notSubmitted' : null } |
  { 'graded' : null } |
  { 'submitted' : null };
export interface SubstituteClass {
  'period' : string,
  'room' : string,
  'classId' : string,
  'mustKnows' : Array<string>,
  'lessonPlan' : string,
  'className' : string,
  'studentCount' : bigint,
}
export interface SubstituteEndOfDay {
  'attendanceTaken' : boolean,
  'presentCount' : bigint,
  'lessonCompletionNotes' : string,
  'incidentCount' : bigint,
  'absentCount' : bigint,
}
export interface Thread {
  'id' : ThreadId,
  'participants' : Array<StaffId>,
  'lastMessageAt' : Timestamp,
  'subject' : string,
  'isDemoData' : boolean,
}
export type ThreadId = bigint;
export type Timestamp = bigint;
export interface TrajectoryResult {
  'priorTermDelta' : [] | [number],
  'direction' : { 'Up' : null } |
    { 'Down' : null } |
    { 'Flat' : null },
  'studentId' : StudentId,
  'rolling3Avg' : number,
  'passStatus' : { 'Passing' : null } |
    { 'Failing' : null } |
    { 'AtRisk' : null },
  'lastFiveScores' : Array<number>,
  'courseId' : CourseId,
}
export interface TrajectoryResult__1 {
  'priorTermDelta' : [] | [number],
  'direction' : { 'Up' : null } |
    { 'Down' : null } |
    { 'Flat' : null },
  'studentId' : string,
  'rolling3Avg' : number,
  'passStatus' : { 'Passing' : null } |
    { 'Failing' : null } |
    { 'AtRisk' : null },
  'lastFiveScores' : Array<number>,
  'courseId' : string,
}
export interface TranscriptCourse {
  'credits' : number,
  'grade' : number,
  'courseName' : string,
  'courseId' : CourseId,
}
export interface TranscriptCourse__1 {
  'credits' : number,
  'term' : string,
  'grade' : number,
  'courseName' : string,
  'courseId' : CourseId,
  'letterGrade' : string,
}
export interface TranscriptTerm {
  'gpa' : number,
  'courses' : Array<TranscriptCourse>,
  'year' : bigint,
  'termId' : string,
}
export interface TranscriptTerm__1 {
  'courses' : Array<TranscriptCourse__1>,
  'termGpa' : number,
  'term' : string,
  'termCredits' : number,
}
export interface UnderstandingSignal {
  'id' : SignalId,
  'studentId' : [] | [StudentId],
  'urgency' : SignalUrgency,
  'createdAt' : Timestamp,
  'commitmentId' : [] | [CommitmentId],
  'roleTarget' : Role,
  'signalType' : SignalType,
  'reason' : string,
}
export interface Unit {
  'id' : UnitId,
  'name' : string,
  'lessons' : Array<Lesson>,
  'courseId' : CourseId,
  'orderIndex' : bigint,
}
export type UnitId = bigint;
export type UpdateResult = { 'ok' : null } |
  { 'err' : string };
export interface UrgentStudent {
  'studentId' : StudentId,
  'urgency' : SignalUrgency,
  'name' : string,
  'reason' : string,
}
export interface WeightedAverageResult {
  'studentId' : StudentId,
  'count' : bigint,
  'average' : number,
  'trajectory' : TrajectoryResult,
  'courseId' : CourseId,
}
export interface _SERVICE {
  '__accounts' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, Account]>
  >,
  '__activities' : ActorMethod<
    [[] | [ActivityId], [] | [bigint]],
    Array<[ActivityId, Activity]>
  >,
  '__activityRosters' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, ActivityRoster]>
  >,
  '__announcements' : ActorMethod<
    [[] | [AnnouncementId], [] | [bigint]],
    Array<[AnnouncementId, Announcement]>
  >,
  '__appointments' : ActorMethod<
    [[] | [AppointmentId], [] | [bigint]],
    Array<[AppointmentId, Appointment]>
  >,
  '__assignments' : ActorMethod<
    [[] | [AssignmentId], [] | [bigint]],
    Array<[AssignmentId, Assignment]>
  >,
  '__assignmentsV2' : ActorMethod<
    [[] | [AssignmentId], [] | [bigint]],
    Array<
      [
        AssignmentId,
        {
          'id' : AssignmentId,
          'categoryId' : CategoryId,
          'pointsPossible' : bigint,
          'name' : string,
          'dueDate' : [] | [string],
          'classId' : CourseId,
        },
      ]
    >
  >,
  '__attendance' : ActorMethod<
    [[] | [AttendanceId], [] | [bigint]],
    Array<[AttendanceId, AttendanceRecord]>
  >,
  '__boardItems' : ActorMethod<
    [[] | [BoardItemId], [] | [bigint]],
    Array<[BoardItemId, BoardItem]>
  >,
  '__channelMsgs' : ActorMethod<
    [[] | [ChannelMsgId], [] | [bigint]],
    Array<[ChannelMsgId, ChannelMessage]>
  >,
  '__channels' : ActorMethod<
    [[] | [ChannelId], [] | [bigint]],
    Array<[ChannelId, Channel]>
  >,
  '__classMeetings' : ActorMethod<
    [[] | [MeetingId], [] | [bigint]],
    Array<[MeetingId, ClassMeeting]>
  >,
  '__commitments' : ActorMethod<
    [[] | [CommitmentId], [] | [bigint]],
    Array<[CommitmentId, Commitment]>
  >,
  '__complianceItems' : ActorMethod<
    [[] | [ComplianceItemId], [] | [bigint]],
    Array<[ComplianceItemId, ComplianceItem]>
  >,
  '__conferenceBookings' : ActorMethod<
    [[] | [ConferenceBookingId], [] | [bigint]],
    Array<[ConferenceBookingId, ConferenceBooking]>
  >,
  '__conferenceSlots' : ActorMethod<
    [[] | [ConferenceSlotId], [] | [bigint]],
    Array<[ConferenceSlotId, ConferenceSlot]>
  >,
  '__courses' : ActorMethod<
    [[] | [CourseId], [] | [bigint]],
    Array<[CourseId, Course]>
  >,
  '__devState' : ActorMethod<[], any>,
  '__enrollments' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, Enrollment]>
  >,
  '__fieldTrips' : ActorMethod<
    [[] | [FieldTripId], [] | [bigint]],
    Array<[FieldTripId, FieldTrip]>
  >,
  '__gradeCategories' : ActorMethod<
    [[] | [CategoryId], [] | [bigint]],
    Array<
      [
        CategoryId,
        {
          'id' : CategoryId,
          'weight' : bigint,
          'name' : string,
          'classId' : CourseId,
        },
      ]
    >
  >,
  '__grades' : ActorMethod<
    [[] | [GradeId], [] | [bigint]],
    Array<[GradeId, Grade]>
  >,
  '__iepNotes' : ActorMethod<
    [[] | [IEPNoteId], [] | [bigint]],
    Array<[IEPNoteId, IEPNote]>
  >,
  '__iepRecords' : ActorMethod<
    [[] | [StudentId], [] | [bigint]],
    Array<[StudentId, IEPRecord]>
  >,
  '__incidents' : ActorMethod<
    [[] | [IncidentId], [] | [bigint]],
    Array<[IncidentId, Incident]>
  >,
  '__interventions' : ActorMethod<
    [[] | [InterventionId], [] | [bigint]],
    Array<[InterventionId, Intervention]>
  >,
  '__messages' : ActorMethod<
    [[] | [MessageId], [] | [bigint]],
    Array<[MessageId, Message]>
  >,
  '__notifications' : ActorMethod<
    [[] | [NotificationId], [] | [bigint]],
    Array<[NotificationId, Notification]>
  >,
  '__permissionSlips' : ActorMethod<
    [[] | [PermissionSlipId], [] | [bigint]],
    Array<[PermissionSlipId, PermissionSlip]>
  >,
  '__readReceipts' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, boolean]>
  >,
  '__scores' : ActorMethod<
    [[] | [ScoreId], [] | [bigint]],
    Array<
      [
        ScoreId,
        {
          'id' : ScoreId,
          'studentId' : StudentId,
          'pointsEarned' : [] | [bigint],
          'assignmentId' : AssignmentId,
        },
      ]
    >
  >,
  '__serviceHours' : ActorMethod<
    [[] | [ServiceEntryId], [] | [bigint]],
    Array<[ServiceEntryId, ServiceHoursEntry]>
  >,
  '__signals' : ActorMethod<
    [[] | [SignalId], [] | [bigint]],
    Array<[SignalId, UnderstandingSignal]>
  >,
  '__staff' : ActorMethod<
    [[] | [StaffId], [] | [bigint]],
    Array<[StaffId, Staff]>
  >,
  '__state' : ActorMethod<[], any>,
  '__studentAudits' : ActorMethod<
    [[] | [AuditId], [] | [bigint]],
    Array<[AuditId, AuditEntry__1]>
  >,
  '__students' : ActorMethod<
    [[] | [StudentId], [] | [bigint]],
    Array<[StudentId, Student]>
  >,
  '__submissions' : ActorMethod<
    [[] | [SubmissionId], [] | [bigint]],
    Array<[SubmissionId, Submission]>
  >,
  '__threads' : ActorMethod<
    [[] | [ThreadId], [] | [bigint]],
    Array<[ThreadId, Thread]>
  >,
  'addFollowUpToIncident' : ActorMethod<
    [IncidentId, bigint, string, RoleContext],
    { 'ok' : Commitment } |
      { 'err' : string }
  >,
  'addIEPNote' : ActorMethod<
    [StudentId, string, IEPNoteType, StaffId],
    UpdateResult
  >,
  'batchRecordAttendance' : ActorMethod<
    [Array<AttendanceRecord>],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'bookConference' : ActorMethod<
    [ConferenceSlotId, string, string],
    { 'ok' : ConferenceBooking } |
      { 'err' : string }
  >,
  'cancelAppointment' : ActorMethod<
    [AppointmentId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'cancelBooking' : ActorMethod<
    [ConferenceBookingId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'checkEligibility' : ActorMethod<
    [string, ActivityId],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'closeIntervention' : ActorMethod<
    [InterventionId, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'computeClassWeightedAverages' : ActorMethod<
    [CourseId],
    Array<StudentWeightedResult>
  >,
  'computeOpportunitySignals' : ActorMethod<
    [RoleContext],
    Array<UnderstandingSignal>
  >,
  'computeRiskSignal' : ActorMethod<[StudentId], [] | [UnderstandingSignal]>,
  'createAnnouncement' : ActorMethod<
    [string, string, Array<Role>, boolean, StaffId],
    { 'ok' : AnnouncementId } |
      { 'err' : string }
  >,
  'createAppointment' : ActorMethod<
    [StudentId, Timestamp, AppointmentType, string],
    { 'ok' : Appointment } |
      { 'err' : string }
  >,
  'createAppointmentForCounsellor' : ActorMethod<
    [StaffId, StudentId, Timestamp, AppointmentType, string],
    { 'ok' : Appointment } |
      { 'err' : string }
  >,
  'createAssignment' : ActorMethod<
    [Assignment, RoleContext],
    { 'ok' : Assignment } |
      { 'err' : string }
  >,
  'createBoardItem' : ActorMethod<
    [string, string, string, [] | [ChannelId]],
    { 'ok' : BoardItem } |
      { 'err' : string }
  >,
  'createChannel' : ActorMethod<
    [string, [] | [string], string, Array<string>],
    { 'ok' : Channel } |
      { 'err' : string }
  >,
  'createCommitment' : ActorMethod<
    [Commitment],
    { 'ok' : Commitment } |
      { 'err' : string }
  >,
  'createFollowUpCommitment' : ActorMethod<
    [CommitmentType, StaffId, StudentId, Timestamp, string],
    { 'ok' : Commitment } |
      { 'err' : string }
  >,
  'createGradeCategory' : ActorMethod<
    [CourseId, string, bigint],
    GradeCategory
  >,
  'createGradebookAssignment' : ActorMethod<
    [CourseId, CategoryId, string, bigint, [] | [string]],
    AssignmentV2
  >,
  'createIntervention' : ActorMethod<
    [StudentId, InterventionType, string, string, Timestamp],
    { 'ok' : Intervention } |
      { 'err' : string }
  >,
  'createInterventionForCounsellor' : ActorMethod<
    [StaffId, StudentId, InterventionType, string, string, Timestamp],
    { 'ok' : Intervention } |
      { 'err' : string }
  >,
  'createSignal' : ActorMethod<
    [UnderstandingSignal],
    { 'ok' : UnderstandingSignal } |
      { 'err' : string }
  >,
  'createStudent' : ActorMethod<
    [Student],
    { 'ok' : Student } |
      { 'err' : string }
  >,
  'createThread' : ActorMethod<
    [Array<StaffId>, string, string, StaffId],
    ThreadId
  >,
  'deleteGradeCategory' : ActorMethod<[CategoryId], boolean>,
  'deleteGradebookAssignment' : ActorMethod<[AssignmentId], boolean>,
  'deleteStudent' : ActorMethod<
    [StudentId, RoleContext],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'detectScheduleConflicts' : ActorMethod<[], Array<string>>,
  'dismissSignal' : ActorMethod<
    [SignalId, RoleContext],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'emitNotification' : ActorMethod<
    [
      StaffId,
      NotificationEventType,
      NotificationTier,
      string,
      string,
      [] | [bigint],
      [] | [string],
    ],
    NotificationId
  >,
  'enrollStudent' : ActorMethod<
    [ActivityId, string],
    { 'ok' : ActivityRoster } |
      { 'err' : string }
  >,
  'exportAttendanceCSV' : ActorMethod<
    [CourseId, [] | [[string, string]]],
    string
  >,
  'exportClassReport' : ActorMethod<[CourseId, string], ClassReport>,
  'exportGradebookCSV' : ActorMethod<[CourseId, string], string>,
  'flagCostBarrier' : ActorMethod<
    [PermissionSlipId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'generateReportCardData' : ActorMethod<[StudentId, string], ReportCardData>,
  'generateSlotsFromTimetable' : ActorMethod<[string], Array<ConferenceSlot>>,
  'generateTimetable' : ActorMethod<[], { 'ok' : bigint } | { 'err' : string }>,
  'getActivities' : ActorMethod<[], Array<Activity>>,
  'getActivityRoster' : ActorMethod<[ActivityId], Array<ActivityRoster>>,
  'getAnnouncements' : ActorMethod<[[] | [Role]], Array<Announcement>>,
  'getAppointments' : ActorMethod<[StaffId], Array<Appointment>>,
  'getAssignmentsByCourse' : ActorMethod<[CourseId, string], Array<Assignment>>,
  'getAssignmentsForCourse' : ActorMethod<[CourseId], Array<Assignment>>,
  'getAttendancePattern' : ActorMethod<[StudentId], AttendancePattern>,
  'getAvailableSlots' : ActorMethod<[string], Array<ConferenceSlot>>,
  'getBoardItems' : ActorMethod<[[] | [ChannelId]], Array<BoardItem>>,
  'getBookingsForParent' : ActorMethod<[string], Array<ConferenceBooking>>,
  'getBookingsForTeacher' : ActorMethod<[string], Array<ConferenceBooking>>,
  'getCaseload' : ActorMethod<[StaffId], Array<CaseloadStudent>>,
  'getCaseloadInsight' : ActorMethod<[StaffId], CaseloadSummary>,
  'getCaseloadStudent' : ActorMethod<
    [StaffId, StudentId],
    { 'ok' : CaseloadEntry } |
      { 'err' : string }
  >,
  'getChannelMessages' : ActorMethod<
    [ChannelId, bigint, bigint],
    Array<ChannelMessage>
  >,
  'getChannels' : ActorMethod<[], Array<Channel>>,
  'getClassGradebook' : ActorMethod<
    [CourseId, string],
    Array<ClassGradebookEntry>
  >,
  'getCoTeacherClasses' : ActorMethod<[string], Array<CoTeacherClassRow>>,
  'getCommitmentById' : ActorMethod<[CommitmentId], [] | [Commitment]>,
  'getCommitmentSurfacing' : ActorMethod<[StaffId], CommitmentSurfacing>,
  'getComplianceItems' : ActorMethod<[StaffId], Array<ComplianceItem>>,
  'getCounsellorCaseload' : ActorMethod<[string], Array<StudentId>>,
  'getCourse' : ActorMethod<[CourseId], [] | [Course]>,
  'getCourseRoster' : ActorMethod<[CourseId], Array<StudentId>>,
  'getCourseWithUnits' : ActorMethod<[CourseId], [] | [Course]>,
  'getCourses' : ActorMethod<[[] | [StaffId]], Array<Course>>,
  'getCurrentRole' : ActorMethod<[], Role>,
  'getCurriculumOverview' : ActorMethod<[], Array<CurriculumCourseRow>>,
  'getDevUser' : ActorMethod<[Role], [] | [Staff]>,
  'getDistrictHealthSummary' : ActorMethod<[], DistrictHealthSummary>,
  'getEarlyWarningRoster' : ActorMethod<
    [],
    Array<
      {
        'flags' : Array<string>,
        'studentId' : StudentId,
        'avgGrade' : number,
        'name' : string,
        'tier' : bigint,
        'attendanceRate' : number,
        'grade' : bigint,
        'incidentCount' : bigint,
      }
    >
  >,
  'getEligibilityThresholds' : ActorMethod<
    [],
    { 'attendanceMin' : number, 'gpaMin' : number }
  >,
  'getFieldTrips' : ActorMethod<[], Array<FieldTrip>>,
  'getHandoffLog' : ActorMethod<[string], Array<HandoffLogEntry>>,
  'getIEP' : ActorMethod<[StudentId], [] | [IEPDetail]>,
  'getIEPCaseload' : ActorMethod<[StaffId], Array<IEPStudent>>,
  'getInbox' : ActorMethod<[StaffId], Array<Thread>>,
  'getIncident' : ActorMethod<[IncidentId], [] | [Incident]>,
  'getIncidentPattern' : ActorMethod<[StudentId], IncidentPattern>,
  'getInterventions' : ActorMethod<[StudentId], Array<Intervention>>,
  'getInterventionsByOwner' : ActorMethod<[StaffId], Array<Intervention>>,
  'getLessonsForUnit' : ActorMethod<[UnitId], Array<Lesson>>,
  'getMasterTimetable' : ActorMethod<[], Array<ClassMeeting>>,
  'getMessages' : ActorMethod<[ThreadId], Array<Message>>,
  'getMorningPicture' : ActorMethod<[], MorningPicture>,
  'getMyAccount' : ActorMethod<[], [] | [Account]>,
  'getNotifications' : ActorMethod<[StaffId], Array<Notification>>,
  'getOverloadFlags' : ActorMethod<
    [[] | [CourseId], [] | [string]],
    Array<OverloadFlag>
  >,
  'getPermissionSlips' : ActorMethod<[FieldTripId], Array<PermissionSlip>>,
  'getReportCard' : ActorMethod<[StudentId, string], ReportCard>,
  'getServiceHours' : ActorMethod<[string], Array<ServiceHoursEntry>>,
  'getSignalContext' : ActorMethod<[SignalId], [] | [UnderstandingSignal]>,
  'getSmartPreFill' : ActorMethod<[CourseId, string], Array<AttendanceRecord>>,
  'getStaffMember' : ActorMethod<[StaffId], [] | [Staff]>,
  'getStaffMembers' : ActorMethod<[], Array<Staff>>,
  'getStudent' : ActorMethod<[StudentId, RoleContext], [] | [Student]>,
  'getStudentAssignments' : ActorMethod<
    [StudentId],
    Array<AssignmentWithStatus>
  >,
  'getStudentAuditTrail' : ActorMethod<[StudentId], Array<AuditEntry__1>>,
  'getStudentCourses' : ActorMethod<[StudentId], Array<CourseId>>,
  'getStudentFullRecord' : ActorMethod<
    [StudentId, RoleContext],
    [] | [StudentFullRecord]
  >,
  'getStudentGradebookSummary' : ActorMethod<
    [StudentId],
    Array<StudentGradebookClassSummary>
  >,
  'getStudentGrades' : ActorMethod<[StudentId], Array<StudentGradeView>>,
  'getStudentRoster' : ActorMethod<[RoleContext], Array<StudentRosterRow>>,
  'getStudentSchedule' : ActorMethod<[StudentId], Array<ClassMeeting>>,
  'getStudentTranscript' : ActorMethod<[StudentId], StudentTranscript>,
  'getSubstituteDayClasses' : ActorMethod<
    [bigint, string],
    Array<SubstituteClass>
  >,
  'getSubstituteEndOfDay' : ActorMethod<[bigint, string], SubstituteEndOfDay>,
  'getTeacherSchedule' : ActorMethod<[StaffId], Array<ClassMeeting>>,
  'getThread' : ActorMethod<[ThreadId], [] | [Thread]>,
  'getThreads' : ActorMethod<[StaffId], Array<Thread>>,
  'getThresholdViolations' : ActorMethod<
    [RoleContext],
    Array<AttendancePattern>
  >,
  'getTrajectory' : ActorMethod<
    [StudentId, [] | [CourseId]],
    Array<TrajectoryResult>
  >,
  'getTranscript' : ActorMethod<[StudentId], Array<TranscriptTerm>>,
  'getUnderstandingSignals' : ActorMethod<[Role, StaffId], Array<SignalCard>>,
  'getUnitsForCourse' : ActorMethod<[CourseId], Array<Unit>>,
  'getUnreadCount' : ActorMethod<[StaffId], bigint>,
  'getUnreadNotificationCount' : ActorMethod<[StaffId], bigint>,
  'getWeightedAverage' : ActorMethod<
    [StudentId, CourseId, string],
    WeightedAverageResult
  >,
  'getWhatNeedsYouToday' : ActorMethod<
    [Role, StaffId],
    Array<UnderstandingSignal>
  >,
  'isDemoDataLoaded' : ActorMethod<[], boolean>,
  'listAttendanceByStudent' : ActorMethod<
    [StudentId, [] | [string], [] | [string]],
    Array<AttendanceRecord>
  >,
  'listCommitmentsByOwner' : ActorMethod<
    [StaffId, [] | [CommitmentStatus]],
    Array<Commitment>
  >,
  'listCommitmentsByStudent' : ActorMethod<[StudentId], Array<Commitment>>,
  'listGradeCategories' : ActorMethod<[CourseId], Array<GradeCategory>>,
  'listGradebookAssignments' : ActorMethod<[CourseId], Array<AssignmentV2>>,
  'listGradesByCourse' : ActorMethod<[CourseId, string], Array<Grade>>,
  'listGradesByStudent' : ActorMethod<
    [StudentId, [] | [CourseId], [] | [string]],
    Array<Grade>
  >,
  'listIncidentsByStudent' : ActorMethod<
    [StudentId, RoleContext],
    Array<Incident>
  >,
  'listIncidentsForRole' : ActorMethod<[RoleContext], Array<Incident>>,
  'listReportableStudents' : ActorMethod<[StaffId], Array<StudentSummary>>,
  'listScores' : ActorMethod<[AssignmentId], Array<Score>>,
  'listScoresByClass' : ActorMethod<[CourseId], Array<Score>>,
  'listSignalsByRole' : ActorMethod<[RoleContext], Array<UnderstandingSignal>>,
  'listStudents' : ActorMethod<
    [bigint, bigint, RoleContext],
    PaginatedStudents
  >,
  'logIncident' : ActorMethod<
    [Incident, RoleContext],
    { 'ok' : Incident } |
      { 'err' : string }
  >,
  'logServiceHours' : ActorMethod<
    [ServiceHoursEntry],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'markAllNotificationsRead' : ActorMethod<
    [StaffId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'markCommitmentComplete' : ActorMethod<
    [CommitmentId],
    { 'ok' : Commitment } |
      { 'err' : string }
  >,
  'markIEPRenewed' : ActorMethod<[StudentId, Timestamp, StaffId], UpdateResult>,
  'markNotificationRead' : ActorMethod<
    [NotificationId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'markRead' : ActorMethod<[MessageId], { 'ok' : null } | { 'err' : string }>,
  'markThreadRead' : ActorMethod<
    [StaffId, ThreadId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'postAnnouncement' : ActorMethod<
    [StaffId, string, string, Array<Role>, AnnouncementPriority],
    AnnouncementId
  >,
  'postMessage' : ActorMethod<
    [ChannelId, string, string, Array<string>, [] | [ChannelMsgId]],
    { 'ok' : ChannelMessage } |
      { 'err' : string }
  >,
  'recordAttendance' : ActorMethod<
    [AttendanceRecord],
    { 'ok' : AttendanceRecord } |
      { 'err' : string }
  >,
  'register' : ActorMethod<
    [Role, bigint, string],
    { 'ok' : Account } |
      { 'err' : string }
  >,
  'replyToAnnouncement' : ActorMethod<
    [AnnouncementId, string, StaffId],
    { 'ok' : MessageId } |
      { 'err' : string }
  >,
  'replyToThread' : ActorMethod<
    [ThreadId, string, StaffId],
    { 'ok' : MessageId } |
      { 'err' : string }
  >,
  'routeIncident' : ActorMethod<
    [IncidentId, string, RoleContext],
    { 'ok' : Incident } |
      { 'err' : string }
  >,
  'sendMessage' : ActorMethod<
    [StaffId, string, string, [] | [ThreadId], StaffId],
    { 'ok' : MessageId } |
      { 'err' : string }
  >,
  'setEligibilityThresholds' : ActorMethod<[number, number], undefined>,
  'setScore' : ActorMethod<[AssignmentId, StudentId, [] | [bigint]], Score>,
  'signPermissionSlip' : ActorMethod<
    [PermissionSlipId, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'submitAssignment' : ActorMethod<
    [StudentId, AssignmentId, string],
    { 'ok' : Submission } |
      { 'err' : string }
  >,
  'surfaceSignalsForRole' : ActorMethod<
    [RoleContext],
    Array<UnderstandingSignal>
  >,
  'switchDevRole' : ActorMethod<[Role], { 'ok' : null } | { 'err' : string }>,
  'togglePin' : ActorMethod<
    [BoardItemId, string],
    { 'ok' : BoardItem } |
      { 'err' : string }
  >,
  'transitionCommitmentStatus' : ActorMethod<
    [CommitmentId, CommitmentStatus, string, RoleContext],
    { 'ok' : Commitment } |
      { 'err' : string }
  >,
  'updateAssignment' : ActorMethod<
    [
      AssignmentId,
      [] | [string],
      [] | [string],
      [] | [Timestamp],
      [] | [number],
      [] | [number],
    ],
    { 'ok' : Assignment } |
      { 'err' : string }
  >,
  'updateCommitmentStatus' : ActorMethod<
    [CommitmentId, CommitmentStatus],
    { 'ok' : Commitment } |
      { 'err' : string }
  >,
  'updateComplianceItem' : ActorMethod<
    [ComplianceItemId, ComplianceStatus, [] | [string]],
    UpdateResult
  >,
  'updateCourse' : ActorMethod<
    [CourseId, [] | [string], [] | [string], [] | [string]],
    { 'ok' : Course } |
      { 'err' : string }
  >,
  'updateGrade' : ActorMethod<
    [Grade, RoleContext],
    { 'ok' : Grade } |
      { 'err' : string }
  >,
  'updateGradeCategory' : ActorMethod<
    [CategoryId, string, bigint],
    [] | [GradeCategory]
  >,
  'updateGradebookAssignment' : ActorMethod<
    [AssignmentId, string, bigint, [] | [string]],
    [] | [AssignmentV2]
  >,
  'updateIEPRenewalDate' : ActorMethod<
    [StudentId, Timestamp, StaffId],
    UpdateResult
  >,
  'updateIncidentStatus' : ActorMethod<
    [IncidentId, IncidentStatus, string, RoleContext],
    { 'ok' : Incident } |
      { 'err' : string }
  >,
  'updateInterventionOutcome' : ActorMethod<
    [InterventionId, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateLesson' : ActorMethod<
    [LessonId, [] | [string], [] | [string]],
    { 'ok' : Lesson } |
      { 'err' : string }
  >,
  'updateScore' : ActorMethod<[ScoreId, [] | [bigint]], [] | [Score]>,
  'updateStudent' : ActorMethod<
    [StudentId, Student],
    { 'ok' : Student } |
      { 'err' : string }
  >,
  'updateUnit' : ActorMethod<
    [UnitId, [] | [string]],
    { 'ok' : Unit } |
      { 'err' : string }
  >,
  'whoami' : ActorMethod<[], Principal>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];